<a class="button" href="<?php echo $this->url(array('league_id' => $this->league->id), 'league_email'); ?>">League Emails</a>
<a class="button" href="<?php echo $this->url(array('league_id' => $this->league->id), 'league_shirts'); ?>">Shirts/Jerseys</a>
<a class="button" href="<?php echo $this->url(array('league_id' => $this->league->id), 'league_emergency'); ?>">Emergency List</a>
<a class="button" href="<?php echo $this->url(array('league_id' => $this->league->id), 'league_players'); ?>">Players List</a>
<a class="button" href="<?php echo $this->url(array('league_id' => $this->league->id), 'league_status'); ?>">Waivers / Paid Status</a>
<a class="button" href="#">Manage Players</a>
