<div class="btn-group">
    <a class="btn btn-small" href="<?php echo $this->url(array('league_id' => $this->league->id), 'league_email'); ?>">League Emails</a>
    <a class="btn btn-small" href="<?php echo $this->url(array('league_id' => $this->league->id), 'league_shirts'); ?>">Shirts/Jerseys</a>
    <a class="btn btn-small" href="<?php echo $this->url(array('league_id' => $this->league->id), 'league_emergency'); ?>">Emergency List</a>
    <?php if($this->userTeams): ?>
    <a class="btn btn-small" href="<?php echo $this->url(array('league_id' => $this->league->id), 'league_userteams'); ?>">Team Requests</a>
    <?php endif; ?>
    <a class="btn btn-small" href="<?php echo $this->url(array('league_id' => $this->league->id), 'league_players'); ?>">Players List</a>
    <a class="btn btn-small" href="<?php echo $this->url(array('league_id' => $this->league->id, 'all' => null), 'league_status'); ?>">Waivers / Paid Status</a>
    <a class="btn btn-small" href="<?php echo $this->url(array('league_id' => $this->league->id), 'league_manage'); ?>">Manage Players</a>
</div>
