<div id="page-banner">&nbsp;</div>

<div class="page-content">
    <div class="row">
        <div class="span12 actions">
            <?php echo $this->partial('league/header.phtml', array('league' => $this->league, 'user' => $this->user, 'userTeams' => $this->userTeams, 'information' => $this->information));?>
        </div>
    </div>
    <div class="row">
        <div class="span12">
            <h2 class="pull-left">
                Coaches List
            </h2>
            <div class="pull-right">
                <?php if($this->isViewable('league_players')): ?>
                <a class="btn btn-mini btn-info" href="<?php echo $this->url(array('league_id' => $this->league->id), 'league_email_coaches'); ?>"><i class="icon-white icon-envelope"></i> Email Incomplete Coaches</a>
                <a class="btn btn-mini btn-info" href="<?php echo $this->url(); ?>?export=1"><i class="icon-list icon-white"></i> Export Data</a>
                <?php endif; ?>
            </div>
            <table class="table table-condensed table-hover">
                <thead>
                    <tr>
                        <th class="span3">Name</th>
                        <th class="span5">Team</th>
                        <th class="span3">Status</th>
                        <th class="span1">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if(count($this->coaches)): ?>
                    <?php foreach($this->coaches as $coach): ?>
                    <tr class="<?php echo ($this->getCoachStatus($coach) == 'Complete') ? 'text-success' : 'text-error'; ?>">
                        <td><?php echo $this->escape($coach['first_name'] . ' ' . $coach['last_name']); ?></td>
                        <td><?php echo $this->escape($coach['name']); ?> (<?php echo $this->escape(ucwords(str_replace('_', ' ', $coach['position']))); ?>)</td>
                        <td><?php echo $this->getCoachStatus($coach); ?></td>
                        <td>
                            <?php if($this->isLeagueCoach($coach)): ?>
                            <a class="btn btn-mini btn-info" href="<?php echo $this->url(array('coach_id' => $coach['id']), 'league_coach_edit'); ?>"><i class="icon-white icon-edit"></i> Edit</a>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                    <?php else: ?>
                    <tr><td colspan="4" style="text-align: center;">No Coaches yet</td></tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="span12">

        </div>
    </div>
</div>
