<?php echo $this->partial('league/header.phtml', array('league' => $this->league, 'user' => $this->user));?>
<h1>Contact Directors, Captains, and Players</h1>

<p>
    You can use this form to contact for information or questions about this
    league.  If you only have the selection of contacting the directors then you
    must be a member of the league and be assigned a team to email your team and
    your captain.
</p>

<div id="contact-container">
    <form id="email-form" method="post">
        <div class="row">
            <?php echo $this->form->from; ?>
        </div>
        <div class="row">
            <?php echo $this->form->to; ?>
        </div>
        <div class="row">
            <?php echo $this->form->subject; ?>
        </div>
        <div class="row">
            <?php echo $this->form->content; ?>
        </div>
        <div class="row">
            <dt>&nbsp;</dt>
            <dd><input id="send-button" class="button" type="submit" value="Send Email" /></dd>
        </div>
    </form>
</div>
