<div id="page-banner">&nbsp;</div>

<div class="page-content">
    <div class="row">
        <div class="span12 actions">
            <?php echo $this->partial('league/header.phtml', array('league' => $this->league, 'user' => $this->user, 'userTeams' => $this->userTeams));?>
        </div>
    </div>
    <div class="row">
        <div class="span12">
            <h2 class="pull-left">
                Emergency Contacts
            </h2>
            <div class="pull-right">
                <a class="btn btn-mini btn-info" href="<?php echo $this->url(); ?>?export=1"><i class="icon-list icon-white"></i> Export Data</a>
            </div>
            <table class="table table-condensed table-hover">
                <thead>
                    <tr>
                        <th class="span4">Player</th>
                        <th class="span6">Contact (Phone)</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->contacts as $userId => $data): ?>
                    <?php if($userId): ?>
                    <tr>
                        <td><?php echo $this->fullname($userId); ?></td>
                        <td>
                            <?php foreach($data as $contact): ?>
                            <?php echo $this->escape($contact['name']); ?> (<?php echo $this->escape($contact['phone']); ?>)<br/>
                            <?php endforeach; ?>
                        </td>
                    </tr>
                    <?php endif; ?>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="span12">

        </div>
    </div>
</div>
