<?php if($this->isLeagueDirector($this->league->id)): ?>
<div class="admin-menu">
    <?php echo $this->partial('league/admin_menu.phtml', array('league' => $this->league));?>
</div>
<?php endif; ?>
<h1 class="league">
    <?php echo $this->leaguename($this->league, true, true, true, true); ?>
</h1>
  
<div class="league-menu">
    <?php echo $this->partial('league/sub_menu.phtml', array('league' => $this->league));?>
</div>
