<div class="row">
    <div class="span12 league-menu">
        <?php echo $this->partial('league/admin_menu.phtml', array('league' => $this->league, 'userTeams' => $this->userTeams));?>
    </div>
</div>
<div class="row">
    <div class="span12">
        <h1 class="align-center">
            <?php echo $this->leaguename($this->league, true, true, true, true); ?>
        </h1>
    </div>
</div>
<div class="row">
    <div class="span12 align-center">
        <?php echo $this->partial('league/sub_menu.phtml', array('league' => $this->league));?>
    </div>
</div>
