<div id="page-banner" class="<?php echo $this->pageClass(); ?>">&nbsp;</div>
<div id="page-header" class="<?php echo $this->pageClass(); ?>">
    <span class="title">
        <h2><?php echo $this->page->title; ?></h2>
    </span>
    <?php if(!$this->page->is_visible): ?>
    <div class="visible">
        *** This page is not yet visible to the public ***
    </div>
    <?php endif; ?>
    <span class="actions">
        <?php if($this->hasRole('admin') or $this->hasRole('editor') or $this->hasRole('editor', $this->page->id)): ?>
        <a class="button" id="add-season" href="#">Add Season</a>
        <div id="add-season-container"></div>
        <?php endif; ?>
    </span>
  
</div>

<div id="page-content" class="<?php echo $this->pageClass(); ?>">
    <?php $i = 0; ?>
    <?php foreach($this->leagues as $league): ?>
    <div class="league">
        <div class="links">
            <?php if($this->hasRole('admin') or $this->hasRole('editor') or $this->hasRole('editor', $this->page->id)): ?>
            <?php if($i != 0): ?>
                <a href="<?php echo $this->url(array('season_id' => $league['id'], 'weight' => $i - 1), 'leagues_move');?>"><img src="<?php echo $this->baseUrl();?>/images/ico-uparrow.png" title="Move Up"/></a>
            <?php endif; ?>
            <?php if($i != count($this->leagues) - 1): ?>
                <a href="<?php echo $this->url(array('season_id' => $league['id'], 'weight' => $i + 1), 'leagues_move');?>"><img src="<?php echo $this->baseUrl();?>/images/ico-downarrow.png" title="Move Down"/></a>
            <?php endif; ?>
                <a href="<?php echo $this->url(array('season_id' => $league['id']), 'leagues_edit');?>"><img src="<?php echo $this->baseUrl();?>/images/ico-edit.png" title="Edit"/></a>
            <?php endif; ?>
            <?php if($this->hasRole('admin')): ?>
                <a onclick="return confirm('Are you sure you want to delete this season?');" href="<?php echo $this->url(array('season_id' => $league['id']), 'leagues_delete');?>"><img src="<?php echo $this->baseUrl();?>/images/ico-delete.png" title="Delete"/></a>
            <?php endif; ?>
            </form>
        </div>
        <div class="name"><a href="<?php echo $this->url(array('type' => $league['name']), 'leagues_view');?>"><?php echo $this->escape(ucwords($league['name']));?> League</a></div>
        <div class="when">( <span class="when-text"><?php echo $this->escape($league['when']);?></span> )</div>
        <div class="information"><?php echo $league['information'];?></div>
    </div>
    <?php $i++; ?>
    <?php endforeach; ?>
</div>
  
<div id="page-links" class="<?php echo $this->pageClass(); ?>">
    <ul>
        <?php foreach($this->links as $link): ?>
        <?php if($link['name'] == substr($this->page->name, -7)): ?>
        <li><?php echo $link['title']; ?></li>
        <?php else: ?>
        <li><a href="<?php echo $this->url(array('type' => $link['name']), 'leagues_view');?>"><?php echo $link['title']; ?></a></li>
        <?php endif; ?>
        <?php endforeach; ?>
        <li><a href="<?php echo $this->url(array(), 'league_waivers');?>">Waivers & Forms</a></li>
    </ul>
</div>
