<div id="page-banner" class="<?php echo $this->pageClass(); ?>">&nbsp;</div>

<div class="row actions">
    <div class="span9 <?php echo $this->pageClass(); ?>">
        <h2><?php echo $this->escape($this->page->title); ?></h2>
    </div>
    <div class="span2">
        <div class="btn-group pull-right">
            <?php if($this->hasRole('admin') or $this->hasRole('manager')): ?>
            <a class="btn btn-small" href="<?php echo $this->url(array(), 'leagues_add'); ?>"><i class="icon-list"></i> Add Season</a>
            <?php endif; ?>
        </div>
    </div>
</div>
<div class="page-content">
    <div class="row">
        <div class="span9">
            <?php foreach($this->leagues as $i => $league): ?>
                <div class="pull-right btn-group">
                        <?php if($this->hasRole('admin') or $this->hasRole('manager') or $this->hasRole('editor') or $this->hasRole('editor', $this->page->id)): ?>
                        <?php if($i != 0): ?>
                            <a class="btn btn-mini" href="<?php echo $this->url(array('season_id' => $league['id'], 'weight' => $i - 1), 'leagues_move');?>"><i class="icon-arrow-up"></i></a>
                        <?php endif; ?>
                        <?php if($i != count($this->leagues) - 1): ?>
                            <a class="btn btn-mini" href="<?php echo $this->url(array('season_id' => $league['id'], 'weight' => $i + 1), 'leagues_move');?>"><i class="icon-arrow-down"></i></a>
                        <?php endif; ?>
                            <a class="btn btn-mini btn-info" href="<?php echo $this->url(array('season_id' => $league['id']), 'leagues_edit');?>"><i class="icon-edit icon-white"></i> Edit</a>
                        <?php endif; ?>
                        <?php if($this->hasRole('admin')): ?>
                            <a class="btn btn-mini btn-danger" onclick="return confirm('Are you sure you want to delete this season?');" href="<?php echo $this->url(array('season_id' => $league['id']), 'leagues_delete');?>"><i class="icon-trash icon-white"></i> Remove</a>
                        <?php endif; ?>
                </div>
                <h2>
                    <a class="leagues" href="<?php echo $this->url(array('type' => $league['name']), 'leagues_view');?>"><?php echo $this->escape(ucwords($league['name']));?> League</a>
                    <small>( <?php echo $this->escape($league['when']);?> )</small>
                </h2>
                <p><?php echo $league['information'];?></p>
                <hr/>
            <?php endforeach; ?>
        </div>
        <div class="span3 page-links">
            <?php echo $this->partial('league-page-links.phtml', array('links' => $this->links, 'page' => $this->page)); ?>
        </div>
    </div>
</div>
