                        <table class="table table-condensed table-hover">
                            <thead>
                                <tr>
                                    <th>Player</th>
                                    <th class="span1">Gender</th>
                                    <th class="span1">Height</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach($this->players as $player): ?>
                                <tr>
                                    <td><a href="<?php echo $this->url(array('user_id' => $player['id']), 'page_profile_public'); ?>"><?php echo $this->fullname($player['id']); ?></a></td>
                                    <td style="text-align: center;"><?php echo (empty($player['gender'])) ? 'Unknown' : $this->escape($player['gender']); ?></td>
                                    <td style="text-align: center;"><?php echo (empty($player['height'])) ? 'Unknown' : $this->escape(floor($player['height'] / 12)) . "'" . $this->escape($player['height'] % 12) .'"'; ?></td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
