<?php echo $this->partial('league/header.phtml', array('league' => $this->league, 'user' => $this->user));?>
<div id="logo">
    <h1>Update Logo for <?php echo $this->escape($this->team->name); ?></h1>

    <form method="post" enctype="multipart/form-data">
    	<p>Select a file to upload for the team logo.  It will be scaled to 85px x 85px</p>
    	<p><input type="file" name="file"/></p>
    	<p><input type="submit" name="upload" value="Upload File"/></p>
	</form>

</div>