<div id="page-banner">&nbsp;</div>

<div class="page-content">
    <div class="row">
        <div class="span12 actions">
            <?php echo $this->partial('league/header.phtml', array('league' => $this->league, 'user' => $this->user, 'userTeams' => $this->userTeams, 'information' => $this->information));?>
        </div>
    </div>
    <div class="row">
        <div class="span11">
            <h2 class="pull-left">Manage League Players</h2>
            <div class="pull-right">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="offset1 span10">
            <p class="alert alert-info">To add a player to this league and require them to answer the registration questions send them this url:<br/><?php echo $this->escape($this->url); ?></p>
        </div>
    </div>
    <div class="row">
        <div class="offset1 span10 well well-small">
            <?php echo $this->addForm; ?>
<!--            <p>You can also manually add them with this button: <a class="btn btn-primary" href="#">Add Player</a> <span class="text-warning">(they will not have registration data)</span></p>-->
        </div>
    </div>
    <div class="row">
        <div class="offset1 span10 well well-small">
            <?php echo $this->removeForm; ?>
        </div>
    </div>
    <div class="row">
        <div class="span12">
            <hr/>
        </div>
    </div>
    <div class="row">
        <div class="span7">
            <h2>Manage Team Rosters</h2>
        </div>
        <div class="span4 align-right">
            <select name="team" onchange="window.location = '<?php echo $this->baseUrl(); ?>/league/<?php echo $this->escape($this->league->id); ?>/manage/' + $(this).val();">
                <option value="0"<?php echo ($this->teamId == 0) ? ' selected' : ''; ?>>Select Team</option>
            <?php foreach($this->teams as $team): ?>
                <option value="<?php echo $this->escape($team->id); ?>"<?php echo ($this->teamId == $team->id) ? ' selected' : ''; ?>><?php echo $this->escape($team->name); ?></option>
            <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="row">
        <form method="post">
            <div class="span4 well well-small" style="height: 350px; overflow: auto;">
                <?php if(count($this->available)): ?>
                <?php foreach($this->available as $data): ?>
                <div class="row">
                    <label class="pull-right btn span3" for="player<?php echo $this->escape($data['id']); ?>">
                        <?php echo $this->escape($data['first_name']) . ' ' . $this->escape($data['last_name']); ?>
                    </label>
                    <input style="margin: 10px;" class="pull-right" id="player<?php echo $this->escape($data['id']); ?>" type="checkbox" name="available[]" value="<?php echo $this->escape($data['id']); ?>"/>
                </div>
                <?php endforeach; ?>
                <?php else: ?>
                <p class="alert">There are no available players</p>
                <?php endif; ?>
            </div>
            <div class="span3 align-center">
                <br/><br/><br/><br/><br/><br/>
                <button class="btn btn-mini btn-info" type="submit" name="manage-add">Add <i class="icon-arrow-right icon-white"></i></button>
                <br/><br/>
                <button class="btn btn-mini btn-info" type="submit" name="manage-remove"><i class="icon-arrow-left icon-white"></i> Remove</button>
                <br/><br/>
                <input type="hidden" name="manage-clear-team" value="<?php echo $this->escape($this->teamId); ?>"/>
                <button class="btn btn-mini btn-warning" type="submit" name="manage-clear"><i class="icon-remove icon-white"></i> Clear Team</button>
            </div>
            <div class="span4 well well-small" style="height: 350px; overflow: auto;">
                <?php if(count($this->teamPlayers)): ?>
                <?php foreach($this->teamPlayers as $data): ?>
                <div class="row">
                    <input style="margin: 10px 5px 10px 25px;" class="pull-right" id="player<?php echo $this->escape($data['id']); ?>" type="checkbox" name="players[]" value="<?php echo $this->escape($data['id']); ?>"/>
                    <label class="pull-right btn span3" for="player<?php echo $this->escape($data['id']); ?>">
                        <?php echo $this->escape($data['first_name']) . ' ' . $this->escape($data['last_name']); ?>
                    </label>
                </div>
                <?php endforeach; ?>
                <?php else: ?>
                <?php if(isset($this->teamId) && $this->teamId != 0): ?>
                <p class="alert">There are no team players</p>
                <?php else: ?>
                <p class="alert">Please select a team to add players to</p>
                <?php endif; ?>
                <?php endif; ?>
            </div>
        </form>
    </div>
</div>
