<?php echo $this->partial('league/header.phtml', array('league' => $this->league, 'user' => $this->user, 'userTeams' => $this->userTeams));?>
<div id="manage">
    <h1>Manage League Players</h1>

    <form method="post">
	    <div id="team-select-div">
			<p>
				<a class="button" href="<?php echo $this->url(array('league_id' => $this->league->id), 'league_move'); ?>">Move Players to Another League</a>
			</p>
            <p>
            <fieldset>
                <legend>Add Players</legend>
                    <select id="add-players" name="players" multiple>
                        <?php foreach($this->users as $user): ?>
                        <option value="<?php echo $this->escape($user->id); ?>"><?php echo $this->escape($user->first_name . ' ' . $user->last_name); ?></option>
                        <?php endforeach; ?>
                    </select>
                    <button id="add-players-button" class="button" type="button">Add Players</button>
                </form>
            </fieldset>
            <fieldset>
                <legend>Remove Players</legend>
                <select id="remove-players" name="players" multiple>
                    <?php foreach($this->leaguePlayers as $user): ?>
                    <option value="<?php echo $this->escape($user['id']); ?>"><?php echo $this->escape($user['first_name'] . ' ' . $user['last_name']); ?></option>
                    <?php endforeach; ?>
                </select>
                <button id="remove-players-button" class="button" type="button">Remove Players</button>
            </fieldset>
            </p>
	    	Select a team:
	    	<select id="teams-select" name="teams-select">
	    		<?php if($this->teamId == 0) { $selected = ' selected="selected"'; } else { $selected = ''; } ?>
	    	    <option value="0"<?php echo $this->escape($selected); ?>>Select a team</option>
	    	<?php foreach($this->teams as $team): ?>
	    		<?php if($this->teamId == $team->id) { $selected = ' selected="selected"'; } else { $selected = ''; } ?>
	    		<option value="<?php echo $this->escape($team->id); ?>"<?php echo $this->escape($selected); ?>><?php echo $this->escape($team->name); ?></option>
	    	<?php endforeach; ?>
	    	</select>
	    </div>
	    <div id="available">

		    <h3>Available Players</h3>
		    <select id="available-select" name="available-select[]" multiple>
		    	<?php foreach($this->available as $data): ?>
		    		<option value="<?php echo $this->escape($data['id']); ?>"><?php echo $this->escape($data['first_name']) . ' ' . $this->escape($data['last_name']); ?></option>
		    	<?php endforeach; ?>
		   	</select>
		</div>
		    
	    <div id="buttons">
	    	<p><input class="button" type="submit" name="add" value="Add =>"/></p>
	    	<p><input class="button" type="submit" name="remove" value="<= Remove"/></p>
	    	<p><input class="button" type="submit" name="clear" value="Clear Team"/></p>
	    </div>

	    <div id="players">
	    	<h3>Team Players</h3>
	    	<select id="players-select" name="players-select[]" multiple>
	    	<?php foreach($this->teamPlayers as $data): ?>
	    		<option value="<?php echo $this->escape($data['id']); ?>"><?php echo $this->escape($data['first_name']) . ' ' . $this->escape($data['last_name']); ?></option>
	    	<?php endforeach; ?>
	    	</select>
	    </div>
    </form>
</div>

<script>
	var leagueId = '<?php echo $this->league->id; ?>';
</script>