<ul id="breadcrumbs">
<?php foreach(array('players' => '1. Select Players to Move', 'target' => '2. Select Target League', 'confirm' => '3. Confirm Move') as $state => $title): ?>
<?php if($this->state == $state): ?>
	<li class="active"><span class="text"><?php echo $this->escape($title); ?></span></li>
<?php else: ?>
	<li><span class="text"><?php echo $this->escape($title); ?></span></li>
<?php endif; ?>
<?php endforeach; ?>
</ul>
<div class="clearfix">&nbsp;</div>