<div id="page-banner">&nbsp;</div>

<div class="row actions">
    <div class="span11">
        <div class="btn-group pull-right">
            <a class="btn btn-small"><i class="icon-plus"></i> Add Question</a>
        </div>
    </div>
</div>
<div class="page-content">
    <div class="row">
        <div class="span12">
            <h2>League Questions</h2>
            <form method="post">
                <table class="table table-condensed table-hover">
                    <thead>
                        <tr>
                            <th class="span9">Question</th>
                            <th class="span1">Type</th>
                            <th class="span2">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $num = count($this->questions) - 1; ?>
                        <?php foreach($this->questions as $i => $question): ?>
                        <tr>
                            <td><?php echo $this->escape($question['title']); ?></td>
                            <td><?php echo $this->escape($question['type']); ?></td>
                            <td style="text-align: right">
                                <?php if($i > 0): ?>
                                <a class="btn btn-mini" href="#"><i class="icon-arrow-up"></i></a>
                                <?php endif; ?>
                                <?php if($i < $num): ?>
                                <a class="btn btn-mini" href="#"><i class="icon-arrow-down"></i></a>
                                <?php endif; ?>
                                <a class="btn btn-mini btn-danger" href="#"><i class="icon-trash icon-white"></i>Remove</a>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <div class="form-actions">
                    <button type="submit" class="btn btn-primary">Save changes</button>
                    <button type="submit" class="btn" name="cancel">Cancel</button>
                </div>
            </form>
        </div>
    </div>
</div>
