<div id="page-banner" class="<?php echo $this->pageClass(); ?>">&nbsp;</div>

<div class="row actions">
    <div class="span9 pull-left <?php echo $this->pageClass(); ?>">
        <h2><?php echo (!empty($this->league)) ? $this->leaguename($this->league['id'], true, false, false, true) : 'No Leagues Yet'; ?></h2>
    </div>
    <div class="span2">
        <div class="btn-group pull-right">
            <?php if($this->isViewable('league_add')): ?>
            <a class="btn btn-small" href="<?php echo $this->url(array('season' => $this->season), 'league_add'); ?>"><i class="icon-book"></i> Add League</a>
            <?php endif; ?>
            <a class="btn btn-small" href="<?php echo $this->url(array('page' => 'leagues'), 'page_view'); ?>"><i class="icon-list"></i> Back to Leagues</a>
        </div>
    </div>
</div>
<div class="page-content">
    <div class="row">
        <div class="span3">
            <?php echo $this->partial('league/league_menu.phtml', array('leagues' => $this->leagues, 'season' => $this->season, 'slug' => $this->slug)); ?>
        </div>
        <div class="span9">
            <?php if(empty($this->league)): ?>
            <p>There are currently no leagues, check back at a later time for leagues.</p>
            <?php else: ?>
            <div class="pull-right">
                <?php if($this->isViewable('league_edit')): ?>
                <a class="btn btn-mini btn-info" href="<?php echo $this->url(array('league_id' => $this->league['id']), 'league_edit');?>"><i class="icon-edit icon-white"></i> Edit League</a>
                <?php endif; ?>

                <?php if($this->isViewable('league_archive')): ?>
                <?php if($this->league['is_archived'] == 0): ?>
                <a class="btn btn-mini btn-danger" onclick="return confirm('Are you sure you want to archive this league?');" href="<?php echo $this->url(array('league_id' => $this->league['id']), 'league_archive');?>"><i class="icon-book icon-white"></i> Archive League</a>
                <?php else: ?>
                <a class="btn btn-mini btn-danger" onclick="return confirm('Are you sure you want to un-archive this league?');" href="<?php echo $this->url(array('league_id' => $this->league['id']), 'league_archive');?>"><i class="icon-book icon-white"></i> Un-Archive League</a>
                <?php endif; ?>
                <?php endif; ?>
            </div>
            <br/>
            <?php if($this->league['visible_from'] > date('Y-m-d H:i:s')): ?>
            <div class="alert">
                *** This page is not yet viewable, it is only viewable to those that can edit it. ***
            </div>
            <?php endif; ?>
            <h3 class="<?php echo $this->pageClass(); ?>"><?php echo $this->leaguename($this->league['id'], true, false, false, true); ?></h3>
            <hr/>
            <div class="pull-right">
                <?php if($this->isViewable('league_description_edit')): ?>
                <a class="btn btn-mini btn-info" href="<?php echo $this->url(array('league_id' => $this->league['id']), 'league_description_edit');?>"><i class="icon-edit icon-white"></i> Edit</a>
                <?php endif; ?>
            </div>
            <?php if(!empty($this->league['info'])): ?>
            <p class="leagues"><?php echo $this->league['info']; ?></p>
            <?php endif; ?>
            <p>
                <?php echo $this->league['information']['description']; ?>
            </p>
            <br/>


            <h3 class="<?php echo $this->pageClass(); ?>"><?php echo $this->leaguename($this->league['id'], false, false, false, true); ?> Information</h3>
            <hr/>
            <div class="pull-right">
                <?php if($this->isViewable('league_information_edit')): ?>
                <a class="btn btn-mini btn-info" href="<?php echo $this->url(array('league_id' => $this->league['id']), 'league_information_edit');?>"><i class="icon-edit icon-white"></i> Edit</a>
                <?php endif; ?>
            </div>
            <dl class="dl-horizontal">
                <dt>&nbsp;</dt>
                <dd>
                    <?php if($this->league['teams'] > 0): ?>
                    <a class="btn btn-info" href="<?php echo $this->url(array('league_id' => $this->league['id']), 'league_view'); ?>">Teams</a>
                    <a class="btn btn-info" href="<?php echo $this->url(array('league_id' => $this->league['id']), 'league_schedule'); ?>">Schedule</a>
                    <a class="btn btn-info" href="<?php echo $this->url(array('league_id' => $this->league['id']), 'league_rankings'); ?>">Rankings</a>
                    <?php elseif($this->isViewable('league_players')): ?>
                    <a class="btn btn-info" href="<?php echo $this->url(array('league_id' => $this->league['id']), 'league_view'); ?>">Event Page</a>
                    <?php endif; ?>
                    <br/><br/>
                </dd>
                <dt>League Director(s):</dt>
                <dd>
                    <?php $i = 1; foreach($this->league['directors'] as $director): ?>
                    <?php if(!empty($this->league['information']['contact_email'])): ?>
                    <?php echo $this->generateEmailLink($this->league['information']['contact_email'], $this->fullname($director['user_id'])); ?>
                    <?php else: ?>
                    <?php echo $this->generateEmailLink($director['user_id'], $this->fullname($director['user_id'])); ?>
                    <?php if($i != sizeof($this->league['directors'])): ?>
                    ,
                    <?php endif; $i++; ?>
                    <?php endif; ?>
                    <?php endforeach; ?>
                </dd>
                <dt>When:</dt>
                <dd>
                    <?php echo $this->escape($this->league['day']); ?>s,
                    <?php echo date('F j', strtotime($this->league['locations']['league']['start']));?> -
                    <?php echo date('F j', strtotime($this->league['locations']['league']['end']));?>
                    <?php echo date('h:i A', strtotime($this->league['locations']['league']['start']));?> -
                    <?php echo date('h:i A', strtotime($this->league['locations']['league']['end']));?>
                </dd>
                <dt>League Location:</dt>
                <dd>
                    <?php echo $this->leagueLocation($this->league['locations']['league']); ?>
                </dd>
                <?php if(isset($this->league['locations']['draft'])): ?>
                <dt>Draft Location:</dt>
                <dd>
                    <?php echo $this->leagueLocation($this->league['locations']['draft']); ?>
                </dd>
                <?php endif; ?>

                <?php if(isset($this->league['locations']['tournament'])): ?>
                <dt>Tournament:</dt>
                <dd>
                    <?php echo $this->leagueLocation($this->league['locations']['tournament']); ?>
                </dd>
                <?php endif; ?>
            </dl>
            <br/>

            <h3 class="<?php echo $this->pageClass(); ?>"><?php echo $this->leaguename($this->league['id'], false, false, false, true); ?> Registration</h3>
            <hr/>
            <div class="pull-right">
                <?php if($this->isViewable('league_registration_edit')): ?>
                <a class="btn btn-mini btn-info" href="<?php echo $this->url(array('league_id' => $this->league['id']), 'league_registration_edit');?>"><i class="icon-edit icon-white"></i> Edit</a>
                <?php endif; ?>
                <?php if($this->isViewable('league_registration_questions_edit')): ?>
                <a class="btn btn-mini btn-info" href="<?php echo $this->url(array('league_id' => $this->league['id']), 'league_registration_questions_edit');?>"><i class="icon-list icon-white"></i> Edit Registration Questions</a>
                <?php endif; ?>
            </div>
            <dl class="dl-horizontal">
                <dt>Status:</dt>
                <dd>
                    <?php echo $this->getLeagueRegistrationStatus($this->league['id']); ?><br/>
                    <?php if($this->isLeagueRegistrationOpen($this->league['id'])): ?>
                        <?php if($this->league['limits']['male_players'] !== null and $this->league['limits']['female_players'] !== null): ?>
                            <?php echo $this->leagueBar('male player spots', $this->league['male_players'], $this->league['limits']['male_players'], $this->league['registration_end']); ?>
                            <?php echo $this->leagueBar('female player sopts', $this->league['female_players'], $this->league['limits']['female_players'], $this->league['registration_end']); ?>
                        <?php elseif($this->league['limits']['total_players'] !== null): ?>
                            <?php echo $this->leagueBar('player spots', $this->league['total_players'], $this->league['limits']['total_players'], $this->league['registration_end']); ?>
                        <?php endif; ?>
                        <?php if($this->league['information']['user_teams'] and $this->league['teams'] < $this->league['limits']['teams']): ?>
                            <?php echo $this->leagueBar('team spots', $this->league['teams'], $this->league['limits']['teams'], $this->league['registration_end']); ?>
                        <?php endif; ?>

                        <a class="btn btn-primary" href="<?php echo $this->url(array('league_id' => $this->league['id']), 'league_register'); ?>">Register for <?php echo $this->leaguename($this->league['id'], false, false, false, true); ?>!</a> <br/><br/>
                    <?php elseif(strstr($this->getLeagueRegistrationMessage($this->league['id']), 'League registration is full with') !== false): ?>
                        <p>You may still register for the waitlist if you like</p>
                        <a class="btn btn-primary" href="<?php echo $this->url(array('league_id' => $this->league['id']), 'league_register'); ?>">Waitlist for <?php echo $this->leaguename($this->league['id'], false, false, false, true); ?></a>
                        <br/><br/>
                    <?php endif; ?>

                </dd>
                <dt>When:</dt>
                <dd>
                    <?php echo date('D, F j h:i:s A', strtotime($this->league['registration_begin'])); ?> -
                    <?php echo date('D, F j h:i:s A', strtotime($this->league['registration_end'])); ?>
                </dd>
                <dt>Cost:</dt>
                <dd>
                    <?php echo ($this->league['information']['cost'] > 0) ? '$ ' . $this->league['information']['cost'] : 'Free'; ?>
                </dd>
                <dt>Waiver:</dt>
                <dd>
                    All players must have a waiver on file with CUPA from a previous
                    <?php echo $this->escape($this->league['year']); ?> league or present a printed
                    and signed copy before play begins.  You may check your status
                    <a href="<?php echo $this->url(array('state' => 'status'), 'profile'); ?>">here</a>.
                </dd>
            </dl>
            <br/>
            <?php endif; ?>
        </div>
    </div>
</div>
