<div id="page-banner">&nbsp;</div>

<div class="row actions">
    <div class="span11">
        <div class="btn-group pull-right">
            <?php echo $this->addQuestionForm; ?>
        </div>
    </div>
</div>
<div class="page-content">
    <div class="row">
        <div class="span12">
            <h2>League Questions</h2>
            <form method="post">
                <table class="table table-condensed table-hover">
                    <thead>
                        <tr>
                            <th class="span8">Question</th>
                            <th class="span1">Required</th>
                            <th class="span3">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $num = count($this->questions) - 1; ?>
                        <?php foreach($this->questions as $i => $question): ?>
                        <tr>
                            <td>
                                <?php echo $this->form->{$question['name']}; ?>
                            </td>
                            <td style="text-align: center;">
                                <a class="btn btn-mini btn-<?php echo ($question['required'] == 1) ? 'success' : 'danger';?>" href="<?php echo $this->url(array('league_id' => $this->league['id'], 'question_id' => $question['id']), 'league_question_toggle_required'); ?>"><i class="icon-<?php echo ($question['required'] == 1) ? 'check' : 'remove';?> icon-white"></i></a>
                            </td>
                            <td style="text-align: right">
                                <?php if($i > 0): ?>
                                <a class="btn btn-mini" href="<?php echo $this->url(array('league_id' => $this->league['id'], 'question_id' => $question['id'], 'direction' => 'up'), 'league_question_move'); ?>"><i class="icon-arrow-up"></i></a>
                                <?php endif; ?>
                                <?php if($i < $num): ?>
                                <a class="btn btn-mini" href="<?php echo $this->url(array('league_id' => $this->league['id'], 'question_id' => $question['id'], 'direction' => 'down'), 'league_question_move'); ?>"><i class="icon-arrow-down"></i></a>
                                <?php endif; ?>
                                <?php if(!in_array($question['name'], $this->requiredQuestions)): ?>
                                <a onclick="return confirm('Are you sure you would like to remove this question?');" class="btn btn-mini btn-danger" href="<?php echo $this->url(array('league_id' => $this->league['id'], 'question_id' => $question['id']), 'league_question_remove'); ?>"><i class="icon-trash icon-white"></i>Remove</a>
                                <?php endif; ?>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <div class="form-actions">
                    <button type="submit" class="btn btn-primary" name="cancel">Back to League</button>
                </div>
            </form>
        </div>
    </div>
</div>
