<div id="page-banner">&nbsp;</div>

<div class="page-content">
    <div class="row">
        <div class="offset1 span10">
            <h2>League Final Rankings</h2>

            <form method="post">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th class="span5">Team</th>
                            <th class="span1" style="text-align: center;">Rank</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->teams as $i => $team): ?>
                        <tr>
                            <td><?php echo $this->escape($team['name']); ?></td>
                            <td style="text-align: center;"><input class="span1" style="text-align: center;" type="text" name="rank[<?php echo $this->escape($team['id']); ?>]" value="<?php echo $this->escape($team['final_rank']); ?>"/></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <div class="form-actions">
                    <button type="submit" class="btn btn-primary" name="save">Save</button>
                    <button type="submit" onclick="return confirm('This will clear the current rankings, are you sure?');" class="btn btn-danger" name="reset">Reset</button>
                    <button type="submit" class="btn" name="cancel">Cancel</button>
                </div>
            </form>
        </div>
    </div>
</div>
