<?php echo $this->partial('league/header.phtml', array('league' => $this->league, 'user' => $this->user, 'userTeams' => $this->userTeams));?>
<div id="teams">
  <?php if(count($this->teams['final'])): ?>
  <h1>Final Team Rankings</h1>
    <?php if($this->isLeagueDirector($this->league->id)): ?>
    <div id="admin-buttons">
        <a class="button" href="<?php echo $this->url(array('league_id' => $this->league->id), 'league_rankings_edit'); ?>">Update Final Rankings</a>
    </div>
    <?php endif; ?>

  <?php foreach($this->teams['final'] as $team): ?>
  <div class="team">
    <?php if($team['color_code']): ?>
    <div class="logo" style="-webkit-box-shadow: 0 0 10px <?php echo $this->escape($team['color_code']); ?>; -moz-box-shadow: 0 0 10px <?php echo $this->escape($team['color_code']); ?>; box-shadow: 0 0 10px <?php echo $this->escape($team->color_code); ?>;">
    <?php else: ?>
    <div class="logo">
    <?php endif; ?>
        <img src="<?php echo $this->baseUrl() . '/images/team_logos/' . $this->getLeagueTeamImage($team['id']); ?>" alt="<?php echo $this->escape($team['name']); ?>"/>
    </div>
    <div class="info">
        <span class="team-name"><?php echo $this->escape($team['name']);?></span><br/>
        <span class="team-color"><strong>Color:</strong> <?php echo $this->escape(ucwords($team['color']));?></span><br/>
        <span class="captains"><strong>Captain(s):</strong>
        <?php $i = 1; $captains = $this->getLeagueTeamCaptains($team->league_id, $team->id); ?>
        <?php foreach($captains as $captain): ?>
            <?php echo $this->fullname($captain->user_id); ?><?php if($i < count($captains)):?>, <?php $i++; endif; ?>
        <?php endforeach; ?>
        </span><br/>
        <span class="captains">
        <strong>League Record:</strong> <?php echo $this->escape($team['record']); ?> (<?php echo $this->getLeagueTeamPointDiff($this->league->id, $team['id']); ?>)<br/>
        </span>
    </div>
    <div class="clearfix"></div>
    <div class="player-container team-<?php echo $this->escape($team['id']); ?>">
    </div>
  </div>
  <?php endforeach; ?>
  <div class="clearfix"></div>
  <?php elseif(count($this->teams['current'])): ?>
  <h1>Current Team Rankings</h1>
    <?php if($this->isLeagueDirector($this->league->id)): ?>
    <div id="admin-buttons">
        <a class="button" href="<?php echo $this->url(array('league_id' => $this->league->id), 'league_rankings_edit'); ?>">Update Final Rankings</a>
    </div>
    <?php endif; ?>
  <?php foreach($this->teams['current'] as $team): ?>
  <div class="team">
    <?php if($team['color_code']): ?>
    <div class="logo" style="-webkit-box-shadow: 0 0 10px <?php echo $this->escape($team['color_code']); ?>; -moz-box-shadow: 0 0 10px <?php echo $this->escape($team['color_code']); ?>; box-shadow: 0 0 10px <?php echo $this->escape($team['color_code']); ?>;">
    <?php else: ?>
    <div class="logo">
    <?php endif; ?>
        <img src="<?php echo $this->baseUrl() . '/images/team_logos/' . $this->getLeagueTeamImage($team['id']); ?>" alt="<?php echo $this->escape($team['name']); ?>"/>
    </div>
    <div class="info">
        <span class="team-name"><?php echo $this->escape($team['name']);?></span><br/>
        <span class="team-color"><strong>Color:</strong> <?php echo $this->escape(ucwords($team['color']));?></span><br/>
        <span class="captains"><strong>Captain(s):</strong>
        <?php $i = 1; $captains = $this->getLeagueTeamCaptains($team['league_id'], $team['id']); ?>
        <?php foreach($captains as $captain): ?>
            <?php echo $this->fullname($captain->user_id); ?><?php if($i < count($captains)):?>, <?php $i++; endif; ?>
        <?php endforeach; ?>
        </span><br/>
        <span class="captains">
        <strong>Record:</strong> <?php echo $this->escape($team['record']); ?> (<?php echo $this->getLeagueTeamPointDiff($this->league->id, $team['id']); ?>)<br/>
        </span>
    </div>
    <div class="clearfix"></div>
    <div class="player-container team-<?php echo $this->escape($team['id']); ?>">
    </div>
  </div>
  <?php endforeach; ?>
  <div class="clearfix"></div>

  <?php else: ?>
  <p align="center">There are no teams defined yet for this league.  Stay tuned...</p>
  <?php endif; ?>
  </div>
</div>
<script>
    var league = '<?php echo $this->league->id; ?>';
</script>
