<div id="page-banner">&nbsp;</div>

<div class="page-content">
    <div class="row">
        <div class="span12 actions">
            <?php echo $this->partial('league/header.phtml', array('league' => $this->league, 'user' => $this->user, 'userTeams' => $this->userTeams));?>
        </div>
    </div>
    <div class="row">
        <div class="span12">
            <h2 class="pull-left"><?php echo (count($this->teams['final'])) ? 'Final' : 'Current'; ?> Team Rankings</h2>
            <div class="pull-right">
                <?php if($this->isLeagueDirector($this->league->id)): ?>
                <a class="btn btn-info btn-mini" href="<?php echo $this->url(array('league_id' => $this->league['id']), 'league_rankings_edit'); ?>"><i class="icon-edit icon-white"></i> Edit Rankings</a>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="span12">
            <?php $teams = (count($this->teams['final'])) ? $this->teams['final'] : $this->teams['current']; ?>
            <?php $num = count($teams) - 1; ?>
            <?php foreach($teams as $i => $team): ?>
            <div class="media">
                <img style="width: 85; height: 85px;" class="pull-left media-object img-polaroid" src="<?php echo $this->baseUrl() . '/images/team_logos/' . $this->getLeagueTeamImage($team['id']); ?>" alt="<?php echo $this->escape($team['name']); ?>"/>
                <div class="media-body">
                    <div class="span8">
                        <h3 class="media-heading" style="text-shadow: 0 0 1px #444; color: <?php echo ($team['color_code']) ? $team['color_code'] : '#222'; ?>"><?php echo $this->escape($team['name']); ?></h3>
                        <strong>Color:</strong> <?php echo $this->escape(ucwords($team['color'])); ?><br/>
                        <strong>Captain(s):</strong>
                        <?php $i = 1; $captains = $this->getLeagueTeamCaptains($team['league_id'], $team['id']); ?>
                        <?php foreach($captains as $captain): ?>
                            <?php echo $this->fullname($captain->user_id); ?><?php if($i < count($captains)):?>, <?php $i++; endif; ?>
                        <?php endforeach; ?>
                    </div>
                    <div class="span2">
                        <h1><small>
                        <?php echo $this->getLeagueTeamRecord($team['league_id'], $team['id']); ?> (<?php echo $this->getLeagueTeamPointDiff($this->league->id, $team['id']); ?>)
                    </small><h1>
                    </div>
                </div>
                <br/>
                <hr/>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>
