<div id="page-banner">&nbsp;</div>

<div class="page-content">
    <div class="row">
        <div class="offset1 span8 pull-left">
            <h3 class="pull-left"><?php echo $this->leaguename($this->league->id, true, true, true, true); ?> <?php echo ($this->waitlist) ? 'Waitlist' : 'Registration'; ?></h3>
        </div>
        <div class="span3 pull-right">
            <a class="btn btn-mini" href="<?php echo $this->url(array('type' => $this->season, 'name' => $this->slugify($this->leaguename($this->league->id, true, false, false, true))), 'leagues_view'); ?>">Back to League</a>
        </div>
    </div>
    <?php if(Zend_Auth::getInstance()->hasIdentity()): ?>
    <div class="row">
        <div class="offset1 span9">
            <?php if($this->state == 'done'): ?>
            <div class="alert alert-warning">
                <h4>Please check your name and email</h4>
                <p>If it is not correct you may go back to change it as well as any other questions.  Once you click '<?php echo ($this->waitlist) ? 'Waitlist' : 'Register'; ?>' you will be <?php echo ($this->waitlist) ? 'waitlisted' : 'registered'; ?> for the league.</p>
            </div>
            <?php endif; ?>
            <?php echo $this->partial('league/register_steps.phtml', array('state' => $this->state));?>
            <?php echo $this->form; ?>
        </div>
    </div>
    <?php else: ?>
    <div class="row">
    <div class="hero-unit span9 offset1">
        <h1>Please Login</h1>
        <p>To register for this league you must first login.  You can login with the link in the upper right of this page.  If you do not have a user account yet you may register for one with the same link.  Just click on the register button.</p>
    </div>
</div>
    <?php endif; ?>
</div>
