<div id="page-banner">&nbsp;</div>

<div class="page-content">
    <div class="row">
        <div class="span12 actions">
            <?php echo $this->partial('league/header.phtml', array('league' => $this->league, 'user' => $this->user, 'userTeams' => $this->userTeams));?>
        </div>
    </div>
    <div class="row">
        <div class="span12">
            <h2 class="pull-left">League Schedule</h2>
            <div class="pull-right">
                <?php if($this->isLeagueDirector($this->league->id)): ?>
                <a class="btn btn-info btn-mini" href="<?php echo $this->url(array('league_id' => $this->league['id']), 'league_schedule_add'); ?>"><i class="icon-plus icon-white"></i>Add a Game</a>
                <a class="btn btn-info btn-mini" href="<?php echo $this->url(array('league_id' => $this->league->id), 'league_schedule_generate'); ?>">Auto Generate Schedule</a>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="span12">
            <ul class="nav nav-pills">
                <li><a>Weeks:</a></li>
            <?php foreach($this->games as $week => $tmp): ?>
                <li class="active"><a href="#week<?php echo $this->escape($week); ?>"><?php echo $this->escape($week); ?></a></li>
            <?php endforeach; ?>
            </ul>
        </div>
    </div>
    <?php foreach($this->games as $week => $games): ?>
    <div class="row">
        <div class="span12">
            <a name="week<?php echo $this->escape($week); ?>"></a>
            <div class="clearfix">
                <h3 class="pull-left">Week <?php echo $this->escape($week); ?></h3>
                <div class="pull-right">
                    <a class="btn btn-mini" href=""><i class="icon-arrow-up"></i> Top</a>
                </div>
            </div>
            <div class="well well-small clearfix">
                <?php foreach($games as $game): ?>
                    <div class="span1">
                        Field #<?php echo $this->escape($game['field']); ?>
                    </div>
                    <div class="span2">
                        <?php echo date('m/d/Y h:i A', strtotime($this->escape($game['day']))); ?>
                    </div>
                    <div class="<?php echo ($this->isLeagueDirector($this->league->id)) ? 'span5' : 'span7'; ?>">
                        <span class="<?php echo $this->displayLeagueGameOutcome($game['id'], $game['away_team_id']);?>">
                            <?php echo $this->escape($game['away_team']); ?>
                        </span>
                        <em class="muted">vs</em>
                        <span class="<?php echo $this->displayLeagueGameOutcome($game['id'], $game['home_team_id']);?>">
                            <?php echo $this->escape($game['home_team']); ?>
                        </span>
                    </div>
                    <div class="span1 align-center">
                        <?php $result = $this->escape($game['away_score']) . ' - ' . $this->escape($game['home_score']); ?>
                        <?php if($result == '0 - 0'): ?>
                        <?php $result = 'N/A'; ?>
                        <?php endif; ?>
                        <?php if($this->isLeagueDirector($this->league->id)): ?>
                        <a title="Edit Score" href="<?php echo $this->url(array('league_id' => $this->league->id, 'game_id' => $game['id']), 'league_schedule_edit'); ?>">
                            <?php echo $result; ?>
                        </a>
                        <?php else: ?>
                        <?php echo $result; ?>
                        <?php endif; ?>
                    </div>
                    <?php if($this->isLeagueDirector($this->league->id)): ?>
                    <div class="span2 align-center">
                        <a class="btn btn-mini btn-danger" onclick="return confirm('Are you sure you would like to remove this game?');" href="<?php echo $this->url(array('league_id' => $this->league->id, 'game_id' => $game['id']), 'league_schedule_delete'); ?>">
                            <i class="icon-trash icon-white"></i> Remove
                        </a>
                    </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    <?php endforeach; ?>
</div>
