<div id="scheduleadd-container">
    <form method="post">
        <div class="row picker">
            <?php echo $this->form->day; ?>
        </div>
        <div class="row">
            <?php echo $this->form->week; ?>
        </div>
        <div class="row">
            <?php echo $this->form->field; ?>
        </div>
        <div class="row chosen">
            <?php echo $this->form->away_team; ?>
        </div>
        <div class="row left chosen">
            <?php echo $this->form->home_team; ?>
        </div>
        <div id="error-string"></div>
    </form>
</div>
