<?php echo $this->partial('league/header.phtml', array('league' => $this->league, 'user' => $this->user, 'userTeams' => $this->userTeams));?>
<div id="shirts">
    <h1>League Jersey/T-Shirt Counts</h1>
    
    <?php if($this->isLeagueDirector($this->league->id) and count($this->shirts) > 1): ?>
    <div id="admin-buttons">
        <a class="button" href="<?php echo $this->url(); ?>?export=1">Export Data</a>
    </div>
    <?php endif; ?>

    <div class="clearfix">&nbsp;<br/>&nbsp;</div>
    
    <?php foreach($this->shirts as $color => $shirt): ?>
    <?php $total = 0; ?>
    <?php foreach($shirt as $count): ?>
    <?php if(is_numeric($count)): ?>
    <?php $total += $count; ?>
    <?php endif; ?>
    <?php endforeach; ?>
    <div class="section">
        <div class="color" style="color: <?php echo $this->escape($shirt['text_code']); ?>; background-color: <?php echo $this->escape($shirt['color_code']); ?>"><?php echo $this->escape($color); ?></div>
        <div class="counts">
            <div class="label">Extra Small:</div>
            <div class="value"><?php echo (isset($shirt['XS'])) ? $this->escape($shirt['XS']) : 0; ?></div>
            <div class="label">Small:</div>
            <div class="value"><?php echo (isset($shirt['S'])) ? $this->escape($shirt['S']) : 0; ?></div>
            <div class="label">Medium:</div>
            <div class="value"><?php echo (isset($shirt['M'])) ? $this->escape($shirt['M']) : 0; ?></div>
            <div class="label">Large:</div>
            <div class="value"><?php echo (isset($shirt['L'])) ? $this->escape($shirt['L']) : 0; ?></div>
            <div class="label">Extra Large:</div>
            <div class="value"><?php echo (isset($shirt['XL'])) ? $this->escape($shirt['XL']) : 0; ?></div>
            <div class="label">2x Extra Large:</div>
            <div class="value"><?php echo (isset($shirt['XXL'])) ? $this->escape($shirt['XXL']) : 0; ?></div>
            <div class="label total">Total:</div>
            <div class="value total"><?php echo $this->escape($total); ?></div>
        </div>
    </div>
    <?php endforeach; ?>
    <?php if(count($this->shirts) == 0): ?>
    <p class="blurb">There are no teams defined so there is no shirt sizes to list.</p>
    <?php endif; ?>
    <div class="clearfix">&nbsp;</div>
</div>
