<div id="page-banner">&nbsp;</div>

<div class="page-content">
    <div class="row">
        <div class="span12 actions">
            <?php echo $this->partial('league/header.phtml', array('league' => $this->league, 'user' => $this->user, 'userTeams' => $this->userTeams));?>
        </div>
    </div>
    <div class="row">
        <div class="span12">
            <h2 class="pull-left">
                Player Statuses
                <small>
                    ** Players in red have unpaid balances. **
                </small>
            </h2>
            <div class="pull-right">
                <a class="btn btn-mini btn-info" href="<?php echo $this->url(array(), 'admin_unpaid'); ?>">Unpaid Details</a>
                <a class="btn btn-mini btn-info" href="<?php echo $this->url(); ?>?export=1"><i class="icon-list icon-white"></i> Export Data</a>
            </div>
            <div class="offset4 span4 btn-group">
                <button class="btn btn-mini<?php echo ($this->all == 'all') ? ' btn-info' : ''; ?>" type="button" onclick="window.location = '<?php echo $this->url(array('league_id' => $this->league->id, 'all' => 'all'), 'league_status'); ?>';">&nbsp; View All &nbsp;</button>
                <button class="btn btn-mini<?php echo ($this->all == 'all') ? '' : ' btn-info'; ?>" type="button" onclick="window.location = '<?php echo $this->url(array('league_id' => $this->league->id, 'all' => null), 'league_status'); ?>';">&nbsp; View Outstanding &nbsp;</button>
            </div>
            <table class="table table-condensed table-hover">
                <thead>
                    <tr>
                        <th class="span7">Player</th>
                        <th class="span1" style="text-align: center;">Wavier</th>
                        <th class="span1" style="text-align: center;">Release</th>
                        <th class="span1" style="text-align: center;">Paid</th>
                        <th class="span1" style="text-align: center;">Balance</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->statuses as $status): ?>
                    <?php if($this->all == 'all' || ($status['paid'] == 0 || $status['release'] == 0 || $status['waiver'] != $this->league->year)): ?>
                    <tr<?php echo ($status['balance'] == NULL) ? '' : ' class="error"'; ?>>
                        <td><?php echo ($status['balance'] == NULL) ? '' : '<span class="text-error">'; ?><?php echo $this->fullname($status['user_id']); ?><?php echo ($status['balance'] == NULL) ? '' : '</span>'; ?></td>
                        <td style="text-align: center;" id="toggle-waiver-<?php echo $this->escape($status['user_id']); ?>">
                            <?php echo $this->generateStatusButton('waiver', $status, $this->league); ?>
                        </td>
                        <td style="text-align: center;" id="toggle-release-<?php echo $this->escape($status['user_id']); ?>">
                            <?php echo $this->generateStatusButton('release', $status, $this->league); ?>
                        </td>
                        <td style="text-align: center;" id="toggle-paid-<?php echo $this->escape($status['user_id']); ?>">
                            <?php echo $this->generateStatusButton('paid', $status, $this->league); ?>
                        </td>
                        <td style="text-align: center;"><?php echo ($status['balance'] == NULL) ? '<span class="text-success">0</span>': '<span class="text-error">' . $status['balance'] . '</span>'; ?></td>
                    </tr>
                    <?php endif; ?>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
function toggle(type, userId, leagueId)
{
    $.ajax({
        url: '<?php echo $this->baseUrl(); ?>/league/' + leagueId + '/status/' + userId + '/toggle/' + type,
        type: 'get',
        success: function(resp) {
            $('#toggle-' + type + '-' + userId).html(resp);
        },
        error: function() {
            alert('Could not save status');
        }
    });
}
</script>
