<div id="page-banner">&nbsp;</div>

<div class="page-content">
    <div class="row">
        <div class="span12 actions">
            <?php echo $this->partial('league/header.phtml', array('league' => $this->league, 'user' => $this->user, 'userTeams' => $this->userTeams));?>
        </div>
    </div>
    <div class="row">
        <div class="span12">
            <h2 class="pull-left">
                Player Statuses
                <small>
                    ** Players in red have unpaid balances. **
                </small>
            </h2>
            <div class="pull-right">
                <a class="btn btn-mini btn-info" href="<?php echo $this->url(array(), 'admin_unpaid'); ?>">Unpaid Details</a>
                <a class="btn btn-mini btn-info" href="<?php echo $this->url(); ?>?export=1">Export Data</a>
            </div>
            <table class="table table-condensed table-hover">
                <thead>
                    <tr>
                        <th class="span7">Player</th>
                        <th class="span1" style="text-align: center;">Wavier</th>
                        <th class="span1" style="text-align: center;">Release</th>
                        <th class="span1" style="text-align: center;">Paid</th>
                        <th class="span1" style="text-align: center;">Balance</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->statuses as $status): ?>
                    <tr<?php echo ($status['balance'] == NULL) ? '' : ' class="error"'; ?>>
                        <td><?php echo ($status['balance'] == NULL) ? '' : '<span class="text-error">'; ?><?php echo $this->fullname($status['user_id']); ?><?php echo ($status['balance'] == NULL) ? '' : '</span>'; ?></td>
                        <td style="text-align: center;"><?php echo ($status['waiver'] == $this->league->year) ? '<button class="btn btn-mini btn-success" type="button" onclick="toggle(\'waiver\', ' . $status['user_id'] . ', ' . $this->league->year . ');"> <i class="icon-check icon-white"></i> </button>' : '<button class="btn btn-mini btn-danger" type="button" onclick="toggle(\'waiver\', ' . $status['user_id'] . ', ' . $this->league->year . ');"><i class="icon-remove icon-white"></i></button>'; ?></td>
                        <td style="text-align: center;"><?php echo ($status['release'] == 1) ? '<button class="btn btn-mini btn-success" type="button" onclick="toggle(\'release\', ' . $status['user_id'] . ', ' . $this->league->id . ');"><i class="icon-check icon-white"></i></button>' : '<button class="btn btn-mini btn-danger" type="button" onclick="toggle(\'release\', ' . $status['user_id'] . ', ' . $this->league->id . ');"><i class="icon-remove icon-white"></i></button>'; ?></td>
                        <td style="text-align: center;"><?php echo ($status['paid'] == 1) ? '<button class="btn btn-mini btn-success" type="button" onclick="toggle(\'paid\', ' . $status['user_id'] . ', ' . $this->league->id . ');"><i class="icon-check icon-white"></i></button>' : '<button class="btn btn-mini btn-danger" type="button" onclick="toggle(\'paid\', ' . $status['user_id'] . ', ' . $this->league->id . ');"><i class="icon-remove icon-white"></i></button>'; ?></td>
                        <td style="text-align: center;"><?php echo ($status['balance'] == NULL) ? '<span class="text-success">0</span>': '<span class="text-error">' . $status['balance'] . '</span>'; ?></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="span12">

        </div>
    </div>
</div>

<script>
function toggle(type, userId, $leagueId)
{

}
</script>
