<a class="button" href="<?php echo $this->url(array('league_id' => $this->league->id), 'league_view'); ?>">Teams</a>
<a class="button" href="<?php echo $this->url(array('league_id' => $this->league->id), 'league_schedule'); ?>">Schedule</a>
<a class="button" href="<?php echo $this->url(array('league_id' => $this->league->id), 'league_rankings'); ?>">Ranking</a>
<a class="button" href="<?php echo $this->url(array('league_id' => $this->league->id), 'league_final'); ?>">Final</a>
