<?php echo $this->partial('league/header.phtml', array('league' => $this->league, 'user' => $this->user));?>
<div id="teams">
  <h1>League Teams</h1>
  <p>Click on the teams to show the players for that team.</p>
  <?php if(count($this->teams)): ?>
  <?php foreach($this->teams as $team): ?>
  <div class="team">
    
    <?php if($team->color_code): ?>
    <div class="logo" style="-webkit-box-shadow: 0 0 10px <?php echo $this->escape($team->color_code); ?>; -moz-box-shadow: 0 0 10px <?php echo $this->escape($team->color_code); ?>; box-shadow: 0 0 10px <?php echo $this->escape($team->color_code); ?>;">
    <?php else: ?>
    <div class="logo">
    <?php endif; ?>
  
      <?php if(file_exists($this->baseUrl() . '/images/team_logos/' . $this->escape($team->id) . '.png')): ?>
      <?php   $imgFile = $this->escape($team->id) . '.png'; ?>
      <?php else: ?>
      <?php   $imgFile = 'default.png'; ?>
      <?php endif; ?>
         
        <img src="<?php echo $this->baseUrl() . '/images/team_logos/' . $imgFile; ?>" alt="<?php echo $this->escape($team->name); ?>"/>
    </div>
    <div class="info" onclick="loadPlayers('<?php echo $this->escape($team->id); ?>')">
        <div class="links">
            <?php if($this->isLeagueDirector($this->league->id)): ?>
            <a href="<?php echo $this->url(array('team_id' => $this->escape($team->id)), 'league_team_edit');?>"><img src="<?php echo $this->baseUrl();?>/images/ico-edit.png" title="Edit League"/></a>
            <a onclick="return confirm('Are you sure you want to delete this team, it will reset all the players associated with this team.');" href="#"><img src="<?php echo $this->baseUrl();?>/images/ico-delete.png" title="Delete League"/></a>
            <?php endif; ?>
        </div>
        <span class="team-name"><?php echo $this->escape($team->name);?></span><br/>
        <span class="team-color"><strong>Color:</strong> <?php echo $this->escape(ucwords($team->color));?></span><br/>
        <span class="captains"><strong>Captain(s):</strong>
        <?php foreach($this->getLeagueTeamCaptains($team->league_id, $team->id) as $captain): ?>
            <?php echo $this->fullname($captain->user_id); ?>
        <?php endforeach; ?>
        </span><br/>
        <span class="captains">
        <strong>Record:</strong> <?php echo $this->getLeagueTeamRecord($team->league_id, $team->id); ?><br/>
        </span>
    </div>
    <div class="clearfix"></div>
    <div class="player-container team-<?php echo $this->escape($team->id); ?>">
    </div>
  </div>
  <?php endforeach; ?>
  <div class="clearfix"></div>
  <?php else: ?>
  <p align="center">There are no teams defined yet for this league.  Stay tuned...</p>
  <?php endif; ?>
  </div>
</div>
