<?php echo $this->partial('league/header.phtml', array('league' => $this->league, 'user' => $this->user, 'userTeams' => $this->userTeams));?>
<div id="teams">
  <h1>League Teams</h1>
    <?php if($this->isLeagueDirector($this->league->id)): ?>
    <div class="admin-buttons">
        <a id="add-team" class="button" href="#">Add a Team</a>
        <div id="add-team-container"></div>
    </div>
    <?php endif; ?>
  <p>Click on the teams to show the players for that team.</p>
  <?php if(count($this->teams)): ?>
  <?php foreach($this->teams as $team): ?>
  <div class="team">

    <?php if($team->color_code): ?>
    <div class="logo" style="-webkit-box-shadow: 0 0 10px <?php echo $this->escape($team->color_code); ?>; -moz-box-shadow: 0 0 10px <?php echo $this->escape($team->color_code); ?>; box-shadow: 0 0 10px <?php echo $this->escape($team->color_code); ?>;">
    <?php else: ?>
    <div class="logo">
    <?php endif; ?>
        <img src="<?php echo $this->baseUrl() . '/images/team_logos/' . $this->getLeagueTeamImage($team->id); ?>" alt="<?php echo $this->escape($team->name); ?>"/>
        <?php if($this->isLeagueCaptain($this->league->id, $team->id) or $this->isLeagueDirector($this->league->id)): ?>
        <div class="overlay" data-link="<?php echo $this->url(array('league_id' => $this->league->id, 'team_id' => $team->id), 'league_logo'); ?>">Upload<br/>Logo</div>
        <?php endif; ?>
    </div>
    <div class="info" onclick="loadPlayers('<?php echo $this->escape($team->id); ?>')">
        <div class="links">
            <?php if($this->isLeagueDirector($this->league->id)): ?>
            <a href="<?php echo $this->url(array('team_id' => $this->escape($team->id)), 'league_team_edit');?>"><img src="<?php echo $this->baseUrl();?>/images/ico-edit.png" title="Edit Team"/></a>
            <a href="<?php echo $this->url(array('team_id' => $this->escape($team->id)), 'league_team_delete');?>" onclick="return confirm('Are you sure you want to delete this team, it will reset ALL DATA associated with this team.');" href="#"><img src="<?php echo $this->baseUrl();?>/images/ico-delete.png" title="Delete Team"/></a>
            <?php endif; ?>
        </div>
        <span class="team-name"><?php echo $this->escape($team->name);?></span><br/>
        <span class="team-color"><strong>Color:</strong> <?php echo $this->escape(ucwords($team->color));?></span><br/>
        <span class="captains"><strong>Captain(s):</strong>
        <?php $i = 1; $captains = $this->getLeagueTeamCaptains($team->league_id, $team->id); ?>
        <?php foreach($captains as $captain): ?>
            <?php echo $this->fullname($captain->user_id); ?><?php if($i < count($captains)):?>, <?php $i++; endif; ?>
        <?php endforeach; ?>
        </span><br/>
        <span class="captains">
        <strong>Record:</strong> <?php echo $this->getLeagueTeamRecord($team->league_id, $team->id); ?> (<?php echo $this->getLeagueTeamPointDiff($this->league->id, $team['id']); ?>)<br/>
        </span>
    </div>
    <div class="clearfix"></div>
    <div class="player-container team-<?php echo $this->escape($team->id); ?>">
    </div>
  </div>
  <?php endforeach; ?>
  <div class="clearfix"></div>
  <?php else: ?>
  <p align="center">There are no teams defined yet for this league.  Stay tuned...</p>
  <?php endif; ?>
  </div>
</div>
<script>
    var league = '<?php echo $this->league->id; ?>';
</script>
