<div id="page-banner">&nbsp;</div>

<div class="page-content">
    <div class="row">
        <div class="span12 actions">
            <?php echo $this->partial('league/header.phtml', array('league' => $this->league, 'user' => $this->user, 'userTeams' => $this->userTeams));?>
        </div>
    </div>
    <div class="row">
        <div class="span12">
            <h2 class="pull-left">League Teams</h2>
            <div class="pull-right">
                <?php if($this->isLeagueDirector($this->league->id)): ?>
                <a class="btn btn-info btn-mini" href="<?php echo $this->url(array('league_id' => $this->league['id']), 'league_team_add'); ?>"><i class="icon-plus icon-white"></i>Add a Team</a>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="span12">
            <?php foreach($this->teams as $i => $team): ?>
            <div class="media">
                <img style="width: 85; height: 85px;" class="pull-left media-object img-polaroid" src="<?php echo $this->baseUrl() . '/images/team_logos/' . $this->getLeagueTeamImage($team->id); ?>" alt="<?php echo $this->escape($team->name); ?>"/>
                <div class="media-body">
                    <div class="span8">
                        <div class="pull-right">
                            <button type="button" onclick="loadPlayers('<?php echo $this->escape($team->id); ?>');"class="btn btn-mini" data-toggle="collapse" data-target="#team<?php echo $this->escape($team->id); ?>"><i class="icon-list icon-white"></i> Show Players</button>
                            <?php if($this->isLeagueDirector($this->league->id) || $this->isLeagueCaptain($this->league->id, $team->id)): ?>
                            <a class="btn btn-mini btn-info" href="<?php echo $this->url(array('team_id' => $this->escape($team->id)), 'league_team_edit');?>"><i class="icon-edit icon-white"></i> Edit</a>
                            <?php endif; ?>
                            <?php if($this->isLeagueDirector($this->league->id)): ?>
                            <a class="btn btn-mini btn-danger" href="<?php echo $this->url(array('team_id' => $this->escape($team->id)), 'league_team_delete');?>" onclick="return confirm('Are you sure you want to delete this team, it will reset ALL DATA associated with this team.');" href="#"><i class="icon-trash icon-white"></i> Remove</a>
                            <?php endif; ?>
                        </div>
                        <h3 class="media-heading" style="text-shadow: 0 0 1px #444; color: <?php echo ($team->color_code) ? $team->color_code : '#222'; ?>"><?php echo $this->escape($team->name); ?></h3>
                        <strong>Color:</strong> <?php echo $this->escape(ucwords($team->color)); ?><br/>
                        <strong>Captain(s):</strong>
                        <?php $i = 1; $captains = $this->getLeagueTeamCaptains($team->league_id, $team->id); ?>
                        <?php foreach($captains as $captain): ?>
                            <?php echo $this->fullname($captain->user_id); ?><?php if($i < count($captains)):?>, <?php $i++; endif; ?>
                        <?php endforeach; ?>
                    </div>
                    <div class="span2">
                        <h1><small>
                        <?php echo $this->getLeagueTeamRecord($team->league_id, $team->id); ?> (<?php echo $this->getLeagueTeamPointDiff($this->league->id, $team['id']); ?>)
                    </small><h1>
                    </div>
                </div>
                <div id="team<?php echo $this->escape($team->id); ?>" class="collapse">
                    <div class="clearfix">&nbsp;</div>
                    <div id="team<?php echo $this->escape($team->id);?>-players" class="span9">
                    </div>
                </div>
                <br/>
                <hr/>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>

<script>
function loadPlayers(teamId)
{
    $.ajax({
        url: '<?php echo $this->baseUrl(); ?>/league/load_players/' + teamId,
        type: 'get',
        success: function(resp) {
            $('#team' + teamId + '-players').html(resp);
        },
        error: function() {
            alert('Could not load players');
        }
    });
}
</script>
