<div id="page-banner">&nbsp;</div>

<div class="page-content">
    <div class="row">
        <div class="span12 actions">
            <?php echo $this->partial('league/header.phtml', array('league' => $this->league, 'user' => $this->user, 'userTeams' => $this->userTeams));?>
        </div>
    </div>
    <div class="row">
        <div class="offset2 span8">
            <h2 class="pull-left">Team Requests</h2>
            <div class="pull-right">
                <a class="btn btn-mini btn-info" href="<?php echo $this->url(); ?>?export=1"><i class="icon-list icon-white"></i>Export Data</a>
            </div>
            <table class="table table-condensed table-hover">
                <thead>
                    <tr>
                        <th class="span4">Player</th>
                        <th class="span4">Requested Team</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->players as $player): ?>
                    <tr>
                        <td><?php echo $this->escape($player['first_name'] . ' ' . $player['last_name']); ?></td>
                        <td><?php echo $this->escape($player['team']); ?></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
