<div id="page-banner">&nbsp;</div>

<div class="page-content">
    <div class="row">
        <div class="span12 actions">
            <?php echo $this->partial('league/header.phtml', array('league' => $this->league, 'user' => $this->user, 'userTeams' => $this->userTeams));?>
        </div>
    </div>
    <div class="row">
        <div class="span12">
            <h2 class="pull-left">
                League Waitlist
            </h2>
            <div class="pull-right">
                <a class="btn btn-mini btn-info" href="<?php echo $this->url(); ?>?export=1"><i class="icon-list icon-white"></i> Export Complete Data</a>
            </div>
            <table class="table table-condensed table-hover">
                <thead>
                    <tr>
                        <th class="span3">Player</th>
                        <th class="span3">Email</th>
                        <th class="span1" style="text-align: center;">Gender</th>
                        <th class="span3" style="text-align: center;">Date</th>
                        <th class="span2" style="text-align: center;">&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->players as $player): ?>
                    <tr>
                        <td><?php echo $this->fullname($player['user_id']); ?></td>
                        <td><?php echo $this->generateEmailLink($player['user_id']); ?></td>
                        <td style="text-align: center;"><?php echo $this->escape($player['profile']['gender']); ?></td>
                        <td style="text-align: center;"><?php echo date('m/d/y h:i:s A', strtotime($player['created_at'])); ?></td>
                        <td style="text-align: center;">
                            <a class="btn btn-mini btn-success" href="<?php echo $this->baseUrl(); ?>/league/<?php echo $this->escape($this->league->id); ?>/waitlist/add/1/member/<?php echo $this->escape($player['id']); ?>"><i class="icon-white icon-check"></i></a>
                            <a class="btn btn-mini btn-danger" onclick="return confirm('Are you sure you want to remove this player?');" href="<?php echo $this->baseUrl(); ?>/league/<?php echo $this->escape($this->league->id); ?>/waitlist/remove/1/member/<?php echo $this->escape($player['id']); ?>"><i class="icon-white icon-remove"</i></a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="span12">

        </div>
    </div>
</div>
