            <div class="row">
                <br/><br/><br/>
            </div>
            <ul class="nav nav-list well well-small">
                <li class="nav-header">Manage Actions</li>
                <li<?php echo ($this->active == 'unpaid') ? ' class="active"' : ''; ?>><a href="<?php echo $this->url(array(), 'manage_unpaid'); ?>">Browser Data</a></li>
                <?php if($this->hasRole('admin') or $this->hasRole('manager')): ?>
                <li<?php echo ($this->active == 'users') ? ' class="active"' : ''; ?>><a href="<?php echo $this->url(array(), 'manage_users'); ?>">Duplicate Users</a></li>
                <li<?php echo ($this->active == 'pages') ? ' class="active"' : ''; ?>><a href="<?php echo $this->url(array(), 'manage_pages'); ?>">Browser Data</a></li>
                <li<?php echo ($this->active == 'volunteers') ? ' class="active"' : ''; ?>><a href="<?php echo $this->url(array(), 'manage_volunteer'); ?>">Duplicate Users</a></li>
                <?php endif; ?>
            </ul>
