<?php echo $this->partial('manage/menu.phtml', array()); ?>
<div id="container">
    <h1>User Management</h1>

    <fieldset>
        <legend>Edit a User</legend>
        <form method="post">
            <select id="users" name="user_id">
                <option value="0">Start typing a name/email</option>
                <?php foreach($this->users as $user): ?>
                <option value="<?php echo $this->escape($user->id); ?>"><?php echo $this->escape($user->first_name . ' ' . $user->last_name); ?> (<?php echo $this->escape($user->email); ?>)</option>
                <?php endforeach; ?>
            </select>
            <input class="button" type="submit" value="Edit User"/>
        </form>
    </fieldset>

    <?php if($this->edit == 1): ?>
    <?php if($this->hasRole('admin')): ?>
    <div class="impersonate">
        <a class="button" href="<?php echo $this->url(array('user' => $this->userEdit->id), 'auth_impersonate_user'); ?>">Become the user <?php echo $this->fullname($this->userEdit->id); ?></a>
    </div>
    <?php endif; ?>

    <div class="edit-form">
        <h2>Edit <?php echo $this->fullname($this->userEdit->id); ?>'s Details</h2>
        <?php echo $this->form; ?>
    </div>
    <?php endif; ?>

</div>

