<h1>All <?php echo $this->category; ?> News</h1>
<?php foreach($this->news as $news): ?>
<div class="row">
    <div class="title">
        <?php echo $news['title']; ?>
    </div>
    <div class="date">
        <?php if($news['posted_at'] == $news['edited_at']): ?>
        <?php echo date('m/d/Y @ h:i:s A', strtotime($news['posted_at'])); ?>
        <?php else: ?>
        <?php echo date('m/d/Y @ h:i:s A', strtotime($news['edited_at'])); ?>
        <?php endif; ?>
    </div>
    <div class="blurb">
        <?php echo $news['info']; ?>
    </div>
    <div class="link">
        <?php if($news['type'] == 'external'): ?>
        <a href="<?php echo $news['url']; ?>">Read More</a>
        <?php endif; ?>
        <?php if($news['type'] == 'internal'): ?>
        <a href="<?php echo $this->baseUrl();?>/<?php echo $news['url']; ?>">Read More</a>
        <?php endif; ?>
        <?php if($news['type'] == 'news'): ?>
        <a href="<?php echo $this->url(array('slug' => $news['slug']), 'news_view'); ?>">Read More</a>
        <?php endif; ?>
    </div>
    <div class="clearfix">&nbsp;</div>
</div>
<?php endforeach; ?>