<div id="page-banner">&nbsp;</div>
<?php if($this->hasRole('admin') or $this->hasRole('reporter')): ?>
<div id="page-actions">
    <a class="button" id="add-news" href="#">Add News</a>
    <div id="add-news-container"></div>
</div>
<?php endif; ?>

<h1>All <?php echo $this->escape($this->category); ?> News</h1>
<?php foreach($this->news as $news): ?>
<div class="news-row">
    <div class="title">
        <a href="<?php echo $this->url(array('slug' => $news['slug']), 'news_view'); ?>"><?php echo $news['title']; ?></a>
    </div>
    <div class="date">
        <?php if($news['posted_at'] == $news['edited_at']): ?>
        <?php echo date('m/d/Y @ h:i:s A', strtotime($news['posted_at'])); ?>
        <?php else: ?>
        <?php echo date('m/d/Y @ h:i:s A', strtotime($news['edited_at'])); ?>
        <?php endif; ?>
    </div>
    <div class="blurb">
        <?php echo $news['info']; ?>
    </div>
    <div class="clearfix">&nbsp;</div>
</div>
<?php endforeach; ?>