<div id="page-banner" class="<?php echo $this->pageClass(); ?>">&nbsp;</div>
<div id="page-header" class="<?php echo $this->pageClass(); ?>">
    <span class="title">
        <h2><?php echo $this->page->title; ?></h2>
    </span>
    <?php if(!$this->page->is_visible): ?>
    <div class="visible">
        *** This page is not yet visible to the public ***
    </div>
    <?php endif; ?>
    <span class="actions">
        <?php if($this->hasRole('admin')): ?>
        <a class="button" href="<?php echo $this->url(array('page' => $this->page->name), 'page_admin'); ?>">Admin</a>
        <?php endif; ?>
        <?php if($this->hasRole('admin') or $this->hasRole('editor') or $this->hasRole('editor', $this->page->id)): ?>
        <a class="button" href="<?php echo $this->url(array('page' => $this->page->name), 'page_edit'); ?>">Edit</a>
        <?php endif; ?>
    </span>
</div>

<div id="page-content" class="<?php echo $this->pageClass(); ?>">
    <h3>Current Active Teams</h3>
    
    <?php foreach($this->activeClubs as $club): ?>
    <div class="club">
        <div class="name"><?php echo $club->name; ?> <span class="club-type">(<?php echo $club->type; ?>)</span></div>
        <div class="date"><?php echo $club->begun; ?> - <?php echo 'Current'; ?></div>
        <div class="website"><?php echo (empty($club->website)) ? '&nbsp;' : '(<a href="' . $club->website . '">Website</a>)'; ?></div>
        <div class="captains"><strong>Captains:</strong> <?php echo (strlen($this->getClubCaptains($club->id)) > 0) ? $this->getClubCaptains($club->id) : 'Unknown'; ?></div>
        <?php if($club->email != null): ?><div class="contact"><strong>Contact Email:</strong> <?php echo $this->displayEmail($club->email); ?></div><?php endif; ?>
        <div class="info"><?php echo $club->content; ?></div>
    </div>
    <?php endforeach; ?>
    
    <h3>Past Teams</h3>
    
    <?php foreach($this->pastClubs as $club): ?>
    <div class="club">
        <div class="name"><?php echo $club->name; ?> <span class="club-type">(<?php echo $club->type; ?>)</span></div>
        <div class="date"><?php echo $club->begun; ?> - <?php echo 'Current'; ?></div>
        <div class="website"><?php echo (empty($club->website)) ? '&nbsp;' : '(<a href="' . $club->website . '">Website</a>)'; ?></div>
        <div class="captains"><strong>Captains:</strong> <?php echo (strlen($this->getClubCaptains($club->id)) > 0) ? $this->getClubCaptains($club->id) : 'Unknown'; ?></div>
        <?php if($club->email != null): ?><div class="contact"><strong>Contact Email:</strong> <?php echo $this->displayEmail($club->email); ?></div><?php endif; ?>
        <div class="info"><?php echo $club->content; ?></div>
    </div>
    <?php endforeach; ?>
</div>
  
<div id="page-links" class="<?php echo $this->pageClass(); ?>">
    <ul>
        <?php foreach($this->links as $link): ?>
        <?php if($link->name == $this->page->name): ?>
        <li><?php echo $link->title; ?></li>
        <?php else: ?>
        <li><a href="<?php echo $this->url(array('page' => $link->name), 'page_view'); ?>"><?php echo $link->title; ?></a></li>
        <?php endif; ?>
        <?php endforeach; ?>
    </ul>
</div>
