<div id="page-banner" class="<?php echo $this->pageClass(); ?>">&nbsp;</div>

<div class="row actions">
    <div class="span9 pull-left <?php echo $this->pageClass(); ?>">
        <h2><?php echo $this->escape($this->page->title); ?></h2>
    </div>
    <div class="span2">
        <div class="btn-group pull-right">
            <?php if($this->hasRole('admin') or $this->hasRole('manager')): ?>
            <a class="btn btn-small" href="<?php echo $this->url(array(), 'page_clubs_add'); ?>"><i class="icon-plus"></i> Add Team</a>
            <?php endif; ?>
        </div>
    </div>
</div>
<div class="page-content">
    <div class="row">
        <div class="span9">
            <p>&nbsp;</p>
            <?php foreach($this->activeClubs as $club): ?>
            <a name="<?php echo $this->escape(strtolower(preg_replace('/\s|\(|\)/', '', $club['name']))); ?>"></a>
                <div class="pull-right">
                <?php echo $this->displayClubRostersLink($club->id); ?>
                <?php if($this->hasRole('admin') or $this->hasRole('editor') or $this->hasRole('editor', $this->page->id) or $this->isClubCaptain($club->id)): ?>
                    <a class="btn btn-info btn-mini" href="<?php echo $this->url(array('club' => $club->id), 'page_clubs_edit'); ?>"><i class="icon-edit icon-white"></i> Edit</a>
                <?php endif; ?>
                <?php if($this->hasRole('admin')): ?>
                    <a class="btn btn-danger btn-mini" onclick="if(!confirm('Are you sure you want to delete the club <?php echo $club->name; ?>?')) { return false; } " href="<?php echo $this->url(array('club' => $club->id), 'page_clubs_delete'); ?>"><i class="icon-trash icon-white"></i> Delete</a>
                <?php endif; ?>
                </div>
                <p>
                    <strong style="font-size: 20pt;"><?php echo $this->escape($club->name); ?></strong><br/>
                    <span class="muted"> A<?php echo ($club->type == 'Open') ? 'n': '';?> <?php echo $this->escape($club->type); ?> Team started in <?php echo $this->escape($club->begin); ?></span><br/>
                    <strong>Captains:</strong> <?php echo (strlen($this->getClubCaptains($club->id)) > 0) ? $this->getClubCaptains($club->id) : 'Unknown'; ?><br/>
                    <?php echo (empty($club->website)) ? '&nbsp;' : 'Web: <a href="' . $this->escape($club->website) . '">' . $this->escape($club->website) . '</a><br/>'; ?>
                    <?php if($club->twitter or $club->facebook): ?>
                        Social:
                        <?php if($club->twitter): ?>
                            <a href="http://twitter.com/<?php echo $club->twitter; ?>">twitter.com/<?php echo $club->twitter; ?></a>
                        <?php endif; ?>
                        <?php if($club->twitter && $club->facebook): ?>
                         ,
                        <?php endif; ?>
                        <?php if($club->facebook): ?>
                            <a href="http://facebook.com/<?php echo $club->facebook; ?>">facebook.com/<?php echo $club->facebook; ?></a>
                        <?php endif; ?>
                </p>
                <?php endif; ?>
                <p>
                    <?php echo $club->content; ?>
                </p>
            <br/>
            <hr/>
            <br/>
            <?php endforeach; ?>
        </div>
        <div class="span3 page-links">
            <?php echo $this->partial('club-page-links.phtml', array('links' => $this->activeClubs, 'page' => $this->page)); ?>
        </div>
    </div>
</div>
