<div id="page-banner"></div>
<div class="row">
    <div class="offset1 span10">
    <p>
        You can use this form to contact for information or issues about the Website
        or general inquiries about CUPA that is not part of the website.  Use the
        select box under To: to select who you would like your message to go to.
    </p>
    </div>
</div>
<div class="row">
    <div class="offset1 span10">
        <?php echo $this->form; ?>
    </div>
</div>
