<div id="page-banner">&nbsp;</div>

<h1>Contact Us</h1>

<p>
    You can use this form to contact for information or issues about the Website
    or general inquiries about CUPA that is not part of the website.  Use the 
    select box under To: to select who you would like your message to go to.
</p>

<div id="contact-container">
    <form method="post">
        <div class="row">
            <?php echo $this->form->from; ?>
        </div>
        <div class="row">
            <?php echo $this->form->to; ?>
        </div>
        <div class="row">
            <?php echo $this->form->subject; ?>
        </div>
        <div class="row">
            <?php echo $this->form->content; ?>
        </div>
        <div class="row">
            <dt>&nbsp;</dt>
            <dd><input class="button" type="submit" value="Send Email" /></dd>
        </div>
    </form>
</div>