<div id="page-banner" class="<?php echo $this->pageClass(); ?>">&nbsp;</div>
<div id="page-header" class="<?php echo $this->pageClass(); ?>">
    <span class="title">
        <h2><?php echo $this->escape($this->page->title); ?></h2>
    </span>
    <?php if(!$this->page->is_visible): ?>
    <div class="visible">
        *** This page is not yet visible to the public ***
    </div>
    <?php endif; ?>
    <span class="actions">
        &nbsp;
    </span>
  
</div>

<div id="page-content" class="<?php echo $this->pageClass(); ?>">
    <?php if(count($this->directors['league'])): ?>
    <h3>League Directors</h3>
    <?php foreach($this->directors['league'] as $directors): ?>
    <?php foreach($directors as $director): ?>
    <div class="director">
        <div class="name"><?php echo $this->fullname($director['user_id']);?></div>
        <div class="league"><?php echo $this->leaguename($director['league_id'], true);?></div>
    </div>
    <?php endforeach; ?>
    <?php endforeach; ?>
    <?php endif; ?>
</div>
  
<?php echo $this->partial('page-links.phtml', array('links' => $this->links, 'page' => $this->page)); ?>
