<div id="page-banner" class="<?php echo $this->pageClass(); ?>">&nbsp;</div>
<div id="page-header" class="<?php echo $this->pageClass(); ?>">
    <span class="title">
        <h2><?php echo $this->escape($this->page->title); ?></h2>
    </span>
    <?php if(!$this->page->is_visible): ?>
    <div class="visible">
        *** This page is not yet visible to the public ***
    </div>
    <?php endif; ?>
    <span class="actions">
        &nbsp;
    </span>

</div>

<div id="page-content" class="<?php echo $this->pageClass(); ?>">
    
    <?php if(count($this->directors['tournament'])): ?>
    <h3 class="pad">Tournaments</h3>
    <?php foreach($this->directors['tournament'] as $userId => $tournaments): ?>
    <div class="director">
        <div class="name"><?php echo $this->fullname($userId); ?></div>
        <div class="league">
            <?php foreach($tournaments as $tournament): ?>
                <a href="<?php echo $this->baseUrl() . $tournament['link']; ?>"><?php echo $this->escape($tournament['name']); ?></a> |
            <?php endforeach; ?>
        </div>
    </div>
    <div class="clearfix"></div>
    <?php endforeach; ?>
    <?php endif; ?>
    
    <hr/>

    <?php if(count($this->directors['league'])): ?>
    <h3>Leagues</h3>
    <?php foreach($this->directors['league'] as $userId => $leagues): ?>
    <div class="director">
        <div class="name"><?php echo $this->fullname($userId); ?></div>
        <div class="league">
            <?php foreach($leagues as $league): ?>
                <a href="<?php echo $this->baseUrl() . $league['link']; ?>"><?php echo $this->escape($league['name']); ?></a> |
            <?php endforeach; ?>

        </div>
    </div>
    <div class="clearfix"></div>
    <?php endforeach; ?>
    <?php endif; ?>

</div>


<?php echo $this->partial('page-links.phtml', array('links' => $this->links, 'page' => $this->page)); ?>
