<div id="page-banner" class="<?php echo $this->pageClass(); ?>">&nbsp;</div>

<div class="row actions">
    <div class="span9 pull-left <?php echo $this->pageClass(); ?>">
        <h2><?php echo $this->escape($this->page->title); ?></h2>
    </div>
    <div class="span2">
        <div class="btn-group pull-right">
        </div>
    </div>
</div>
<div class="page-content">
    <div class="row">
        <div class="span9">
            <?php if(count($this->tournaments) > 0): ?>
            <h2>Tournaments</h2>
            <?php foreach($this->tournaments as $tournament): ?>
            <h4><?php echo $tournament['name']; ?> -
            <?php $cnt = 0; ?>
            <?php foreach($tournament['directors'] as $name => $email): ?>
            <?php if($cnt > 0):?>,<?php endif; ?>
            <?php echo $this->generateEmailLink($email, $name); ?>
            <?php $cnt++; ?>
            <?php endforeach; ?>
            <?php endforeach; ?>
            <?php endif; ?>

            <hr/>

            <?php if(count($this->leagues) > 0): ?>
            <h2>Leagues</h2>
            <?php foreach($this->leagues as $league): ?>
            <h4><?php echo $league['name']; ?> -
            <?php $cnt = 0; ?>
            <?php foreach($league['directors'] as $name => $email): ?>
            <?php if($cnt > 0):?>,<?php endif; ?>
            <?php echo $this->generateEmailLink($email, $name); ?>
            <?php $cnt++; ?>
            <?php endforeach; ?>
            <?php endforeach; ?>
            <?php endif; ?>

        </div>
        <div class="span3 page-links">
            <?php echo $this->partial('page-links.phtml', array('links' => $this->links, 'page' => $this->page)); ?>
        </div>
    </div>
</div>
