<div id="page-banner">&nbsp;</div>

<h1>Edit <?php echo $this->escape($this->page->title); ?></h1>
<form method="post">
    <div id="edit-container">
        <div class="row">
            <?php echo $this->form->title; ?>
        </div>
        <div class="row">
            <?php echo $this->form->url; ?>
        </div>
        <div class="row">
            <?php echo $this->form->target; ?>
        </div>
        <div class="row">
            <?php echo $this->form->weight; ?>
        </div>
        <div class="row">
            <?php echo $this->form->content; ?>
        </div>

    </div>
    <div id="buttons-container">
        <input class="button" type="submit" value="Save"/>
        <a class="button button-red" href="<?php echo $this->url(array('page' => $this->page->name), 'page_view'); ?>">Cancel</a>
    </div>
</form>
<?php echo $this->partial('tinymce.phtml', array('element' => 'content', 'css' => '/css/page/view.css')); ?>
