<div id="page-banner" class="<?php echo $this->pageClass(); ?>">&nbsp;</div>

<div class="row actions">
    <div class="span9 pull-left <?php echo $this->pageClass(); ?>">
        <h2><?php echo $this->escape($this->page->title); ?></h2>
    </div>
    <div class="span2">
        <div class="btn-group pull-right">
            <?php if($this->hasRole('admin') or $this->hasRole('manager')): ?>
            <a class="btn btn-small" href="<?php echo $this->url(array(), 'page_minutes_add'); ?>"><i class="icon-list"></i> Add Minutes</a>
            <?php endif; ?>
        </div>
    </div>
</div>
<div class="page-content">
    <div class="row">
        <div class="span9">
            <br/>
            <p>Here is a list of all the board meeing with the notes if available.</p>

            <ul class="nav nav-tabs">
                <li class="active"><a href="#visible" data-toggle="tab">Meeting Minutes</a></li>
                <?php if(($this->hasRole('admin') or $this->hasRole('manager')) and !empty($this->minutes['hidden'])): ?>
                <li><a href="#hidden" data-toggle="tab">Hidden Meeting Minutes</a></li>
                <?php endif; ?>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="visible">
                    <table class="table table-condensed table-hover">
                        <thead>
                            <tr>
                                <th>When</th>
                                <th>Where</th>
                                <?php if($this->hasRole('admin') or $this->hasRole('manager') or $this->hasRole('editor') or $this->hasRole('editor', $this->page->id)): ?>
                                <th>Actions</th>
                                <?php else: ?>
                                <th>Download</th>
                                <?php endif; ?>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($this->minutes['visible'] as $minute): ?>
                            <tr>
                                <td><?php echo $this->escape(date('m/d/Y h:i:s A', strtotime($minute['when']))); ?></td>
                                <td><?php echo $this->escape($minute['location']); ?></td>
                                <td>
                                    <?php if($minute['pdf'] != null): ?>
                                    <a class="btn btn-small" href="<?php echo $this->url(array('minute' => $minute['id']), 'page_minutes_download'); ?>">
                                        <i class="icon-download"></i> Download
                                    </a>
                                    <?php endif; ?>
                                    <?php if($this->hasRole('admin') or $this->hasRole('manager') or $this->hasRole('editor') or $this->hasRole('editor', $this->page->id)): ?>
                                    <a class="btn btn-small btn-info" href="<?php echo $this->url(array('minute' => $minute['id']), 'page_minutes_edit'); ?>">
                                        <i class="icon-edit icon-white"></i> Edit
                                    </a>
                                    <?php endif; ?>
                                    <?php if($this->hasRole('admin')): ?>
                                    <a class="btn btn-small btn-danger" onclick="return confirm('Are you sure you would like to delete these minutes?');"href="<?php echo $this->url(array('minute' => $minute['id']), 'page_minutes_delete'); ?>">
                                        <i class="icon-trash icon-white"></i> Delete
                                    </a>
                                    <?php endif; ?>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
                <?php if(($this->hasRole('admin') or $this->hasRole('editor') or $this->hasRole('editor', $this->page->id)) and !empty($this->minutes['hidden'])): ?>
                <div class="tab-pane" id="hidden">
                    <table class="table table-condensed table-hover">
                        <thead>
                            <tr>
                                <th>When</th>
                                <th>Where</th>
                                <?php if($this->hasRole('admin') or $this->hasRole('editor') or $this->hasRole('editor', $this->page->id)): ?>
                                <th>Actions</th>
                                <?php else: ?>
                                <th>Download</th>
                                <?php endif; ?>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($this->minutes['hidden'] as $minute): ?>
                            <tr>
                                <td><?php echo $this->escape(date('m/d/Y h:i:s A', strtotime($minute['when']))); ?></td>
                                <td><?php echo $this->escape($minute['location']); ?></td>
                                <td>
                                    <?php if($minute['pdf'] != null): ?>
                                    <a class="btn btn-small" href="<?php echo $this->url(array('minute' => $minute['id']), 'page_minutes_download'); ?>">
                                        <i class="icon-download"></i> Download
                                    </a>
                                    <?php endif; ?>
                                    <?php if($this->hasRole('admin') or $this->hasRole('editor') or $this->hasRole('editor', $this->page->id)): ?>
                                    <a class="btn btn-small btn-info" href="<?php echo $this->url(array('minute' => $minute['id']), 'page_minutes_edit'); ?>">
                                        <i class="icon-edit icon-white"></i> Edit
                                    </a>
                                    <a class="btn btn-small btn-danger" href="<?php echo $this->url(array('minute' => $minute['id']), 'page_minutes_delete'); ?>">
                                        <i class="icon-trash icon-white"></i> Delete
                                    </a>
                                    <?php endif; ?>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>                </div>
                <?php endif; ?>
            </div>

        </div>
        <div class="span3 page-links">
            <?php echo $this->partial('page-links.phtml', array('links' => $this->links, 'page' => $this->page)); ?>
        </div>
    </div>
</div>
