<div id="page-banner">&nbsp;</div>

<h1>Edit News</h1>

<div id="newsedit-contianer">
    <form method="post">
        <div class="row">
            <?php echo $this->form->is_visible; ?>
        </div>
        <div class="row">
            <?php echo $this->form->category; ?>
        </div>
        <div class="row">
            <?php echo $this->form->title; ?>
        </div>
        <div class="row">
            <dt>Slug:</dt>
            <dd class="disabled"><?php echo $this->news->slug; ?></dd>
        </div>
        <div class="row">
            <?php echo $this->form->url; ?>
        </div>
        <div class="row">
            <?php echo $this->form->info; ?>
        </div>
        <div class="row">
            <?php echo $this->form->remove_at; ?>
        </div>
        <div class="row">
            <?php echo $this->form->content; ?>
        </div>
        
        <div id="buttons-container">
            <input class="button" type="submit" value="Save"/>
            <a class="button button-red" href="<?php echo $this->url(array('slug' => $this->news->slug), 'news_view'); ?>">Cancel</a>
        </div>
    </form>
    
    <?php echo $this->partial('tinymce.phtml', array('element' => 'content')); ?>

</div>