<?php foreach($this->data as $category => $item): ?>

<?php if($item['type'] == 'internal'): ?>
    <h3><?php echo $item['title']; ?> (<a href="<?php echo $this->baseUrl(); ?>/<?php echo $item['url']; ?>">Info</a>)</h3>
<?php endif; ?>

<?php if($item['type'] == 'external'): ?>
    <h3><?php echo $item['title']; ?> (<a href="<?php echo $item['url']; ?>">Info</a>)</h3>
<?php endif; ?>

<?php if($item['type'] == 'news'): ?>
    <h3><?php echo $item['title']; ?> (<a href="<?php echo $this->url(array('news' => $item['id']), 'news_view'); ?>">More</a>)</h3>
<?php endif; ?>

<?php if($item['type'] == 'text'): ?>
    <h3><?php echo $item['title']; ?></h3>
<?php endif; ?>
    <p><?php echo $item['info']; ?></p>
<?php endforeach; ?>