<div id="page-banner">&nbsp;</div>

<div class="back">
    <?php if($this->hasRole("reporter") or $this->hasRole('admin')): ?>
    <a class="button" href="<?php echo $this->url(array('slug' => $this->news->slug), 'news_edit'); ?>">Edit News</a>
    <?php endif; ?>
    <a class="button" href="<?php echo $this->escape($this->backUrl); ?>">Back</a>
</div>

<div class="title">
    <?php echo $this->news->title; ?><br/>
</div>

<?php if(!$this->news->is_visible): ?>
<div class="visible">
    *** This news item is not yet visible to the public ***
</div>
<?php endif; ?>

<div class="subtitle">
    <?php if($this->news->posted_at == $this->news->edited_at): ?>
    Posted by <?php echo $this->fullname($this->news->posted_by); ?> on <?php echo date('m/d/Y @ h:i:s A', strtotime($this->news->posted_at)); ?>
    <?php else: ?>
    Updated by <?php echo $this->fullname($this->news->last_edited_by); ?> on <?php echo date('m/d/Y @ h:i:s A', strtotime($this->news->edited_at)); ?>
    <?php endif; ?>
    
</div>

<div class="content">
    <?php echo $this->news->content; ?>
</div>

<div class="clearfix">&nbsp;</div>