<div id="page-banner" class="<?php echo $this->pageClass(); ?>">&nbsp;</div>
<div id="page-header" class="<?php echo $this->pageClass(); ?>">
    <span class="title">
        <h2><?php echo $this->escape($this->page->title); ?></h2>
    </span>
    <?php if(!$this->page->is_visible): ?>
    <div class="visible">
        *** This page is not yet visible to the public ***
    </div>
    <?php endif; ?>
    <span class="actions">
        <?php if($this->hasRole('admin') or $this->hasRole('editor') or $this->hasRole('editor', $this->page->id)): ?>
        <a class="button" id="add-officer" href="#">Add Officer</a>
        <div id="add-officers-container"></div>
        <?php endif; ?>
    </span>
  
</div>

<div id="page-content" class="<?php echo $this->pageClass(); ?>">

<h2>Current Board Members</h2>
<?php foreach(array_merge($this->officers['current'], $this->officers['atLarge']) as $officer): ?>
<div class="officer">
    <div class="image"><img src="<?php echo $this->officerImageUrl($officer['user_id']); ?>"/></div>
    <div class="info">
        <div class="links">
            <?php if($this->hasRole('admin') or $this->hasRole('editor') or $this->hasRole('editor', $this->page->id)): ?>
            <a href="<?php echo $this->url(array('officer' => $officer['id']), 'page_officers_edit'); ?>">
                <img src="<?php echo $this->baseUrl(); ?>/images/ico-edit.png"/>
            </a>
            <?php endif; ?>
            <?php if($this->hasRole('admin')): ?>
            <a onclick="if(!confirm('Are you sure you would like to delete this officer?')) { return false; }" href="<?php echo $this->url(array('officer' => $officer['id']), 'page_officers_delete'); ?>">
                <img src="<?php echo $this->baseUrl(); ?>/images/ico-delete.png"/>
            </a>
            <?php endif; ?>
        </div>
        <span class="name"><?php echo $this->fullname($officer['user_id']); ?></span><br/>
        <span class="position"><?php echo $this->escape($officer['position']); ?></span></br>
        <span class="since">Since: <?php echo date('M dS, Y', strtotime($officer['since'])); ?></span>
    </div>
</div>
<?php endforeach; ?>

<?php if($this->hasRole('admin') and isset($this->officers['past'])): ?>
<h2>Past Board Members</h2>
<?php foreach($this->officers['past'] as $officer): ?>
<div class="officer">
    <div class="image"><img src="<?php echo $this->officerImageUrl($officer['user_id']); ?>"/></div>
    <div class="info">
        <div class="links">
            <?php if($this->hasRole('admin') or $this->hasRole('editor') or $this->hasRole('editor', $this->page->id)): ?>
            <a href="<?php echo $this->url(array('officer' => $officer['id']), 'page_officers_edit'); ?>">
                <img src="<?php echo $this->baseUrl(); ?>/images/ico-edit.png"/>
            </a>
            <?php endif; ?>
            <?php if($this->hasRole('admin')): ?>
            <a onclick="if(!confirm('Are you sure you would like to delete this officer?')) { return false; }" href="<?php echo $this->url(array('officer' => $officer['id']), 'page_officers_delete'); ?>">
                <img src="<?php echo $this->baseUrl(); ?>/images/ico-delete.png"/>
            </a>
            <?php endif; ?>
        </div>
        <span class="name"><?php echo $this->fullname($officer['user_id']); ?></span><br/>
        <span class="position"><?php echo $this->escape($officer['position']); ?></span></br>
        <span class="since"><?php echo date('M dS, Y', strtotime($officer['since'])); ?> - <?php echo date('M dS, Y', strtotime($officer['to'])); ?></span>
    </div>
</div>
<?php endforeach; ?>
<?php endif; ?>
</div>

<?php echo $this->partial('page-links.phtml', array('links' => $this->links, 'page' => $this->page)); ?>
