<div id="page-banner" class="<?php echo $this->pageClass(); ?>">&nbsp;</div>

<div class="row actions">
    <div class="span9 pull-left <?php echo $this->pageClass(); ?>">
        <h2><?php echo $this->escape($this->page->title); ?></h2>
    </div>
    <div class="span2">
        <div class="btn-group pull-right">
            <?php if($this->isViewable('page_officers_add')): ?>
            <a class="btn btn-small" href="<?php echo $this->url(array(), 'page_officers_add'); ?>"><i class="icon-user"></i> Add Officer</a>
            <?php endif; ?>
        </div>
    </div>
</div>
<div class="page-content">
    <div class="row">
        <div class="span9">
            <?php foreach(array_merge($this->officers['current'], $this->officers['atLarge']) as $officer): ?>
            <div class="row">
                <div class="span2">
                    <img class="well well-small" src="<?php echo $this->officerImageUrl($officer['user_id']); ?>"/>
                </div>
                <div class="span7">
                    <ul class="officers">
                        <li class="name"><?php echo $this->fullname($officer['user_id']); ?></li>
                        <li class="position"><?php echo $this->escape($officer['position']); ?></li>
                        <li>
                            <?php if($officer['position'] != 'At Large Board Member'): ?>
                            <?php echo $this->generateEmailLink(strtolower(str_replace(' ', '-', $officer['position'])) . '@cincyultimate.org'); ?>
                            <?php else: ?>
                            <?php echo $this->generateEmailLink($officer['user_id'], $this->fullname($officer['user_id'])); ?>
                            <?php endif; ?>
                        </li>
                        <li class="since">Starting <?php echo date('F d, Y', strtotime($officer['since'])); ?></li>
                        <li>
                            <?php if($this->isViewable('page_officers_edit')): ?>
                            <a class="btn btn-info btn-mini" href="<?php echo $this->url(array('officer' => $officer['id']), 'page_officers_edit'); ?>">
                                <i class="icon-edit icon-white"></i> Edit
                            </a>
                            <?php endif; ?>
                            <?php if($this->isViewable('page_officers_delete')): ?>
                            <a class="btn btn-danger btn-mini" onclick="if(!confirm('Are you sure you would like to delete this officer?')) { return false; }" href="<?php echo $this->url(array('officer' => $officer['id']), 'page_officers_delete'); ?>">
                                <i class="icon-trash icon-white"></i> Remove
                            </a>
                            <?php endif; ?>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="offset1 span8"><?php echo $officer['description']; ?></div>
            </div>
            <hr/>
            <?php endforeach; ?>
        </div>
        <div class="span3 page-links">
            <?php echo $this->partial('page-links.phtml', array('links' => $this->links, 'page' => $this->page)); ?>
        </div>
    </div>
</div>
