<div id="page-banner">&nbsp;</div>

<h1>Edit <?php echo $this->pickup->title; ?></h1>
<form method="post">
    <div id="pickupedit-container">
        <div class="row">
            <?php echo $this->form->title; ?>
        </div>
        <div class="row">
            <?php echo $this->form->day; ?>
        </div>
        <div class="row">
            <?php echo $this->form->time; ?>
        </div>
        <div class="row">
            <?php echo $this->form->info; ?>
        </div>
        <div class="row">
            <?php echo $this->form->user_id; ?>
        </div>
        <div class="row">
            <?php echo $this->form->email; ?>
        </div>
        <div class="row">
            <?php echo $this->form->location; ?>
        </div>
        <div class="row">
            <?php echo $this->form->map; ?>
        </div>
        <div class="row">
            <?php echo $this->form->weight; ?>
        </div>
        <div class="row">
            <?php echo $this->form->is_visible; ?>
        </div>
    </div>
    <div id="buttons-container">
        <input class="button" type="submit" value="Save"/>
        <a class="button button-red" href="<?php echo $this->url(array(), 'page_pickup'); ?>">Cancel</a>
    </div>
</form>
<?php echo $this->partial('tinymce.phtml', array('element' => 'info')); ?>
