<div id="page-banner" class="<?php echo $this->pageClass(); ?>">&nbsp;</div>

<div class="row actions">
    <div class="span9 pull-left <?php echo $this->pageClass(); ?>">
        <h2><?php echo $this->escape($this->page->title); ?></h2>
    </div>
    <div class="span2">
        <div class="btn-group pull-right">
            <?php if($this->isViewable('page_pickup_add')): ?>
            <a class="btn btn-small" href="<?php echo $this->url(array(), 'page_pickup_add'); ?>"><i class="icon-plus"></i> Add Pickup</a>
            <?php endif; ?>
            <?php if($this->isViewable('page_tournament_add')): ?>
            <a class="btn btn-small" href="<?php echo $this->url(array(), 'page_tournament_add'); ?>"><i class="icon-plus"></i> Add Tournament</a>
            <?php endif; ?>
        </div>
    </div>
</div>
<div class="page-content">
    <div class="row">
        <div class="span9">
            <h3>CUPA Sponsored Tournaments</h3>
            <?php foreach($this->tournaments as $tournament): ?>
            <p>
                <a href="<?php echo $this->url(array('name' => $tournament['name']), 'tournament_home'); ?>"><?php echo $this->escape($tournament['display_name']); ?></a> -
                <?php if($tournament['start'] == $tournament['end']): ?>
                <?php echo $this->escape(date('F jS Y', strtotime($tournament['start']))); ?>
                <?php else: ?>
                <?php echo $this->escape(date('F jS', strtotime($tournament['start']))); ?> - <?php echo $this->escape(date('jS Y', strtotime($tournament['end']))); ?>
                <?php endif; ?>
            </p>
            <?php endforeach; ?>
            <br/>
            <br/>
            <h3>Pickup Ultimate Around Town</h3>
            <?php foreach($this->pickups as $pickup): ?>
            <?php if($pickup->is_visible == 0 && !$this->isViewable('page_pickup_edit')) { continue; } ?>

            <?php if($pickup->is_visible == 0): ?>
            <div class="alert alert-warning">This pickup is not visible yet.</div>
            <?php endif; ?>
            <div class="pull-right">
                <?php if($this->isViewable('page_pickup_edit')): ?>
                <a class="btn btn-info btn-mini" href="<?php echo $this->url(array('pickup' => $pickup['id']), 'page_pickup_edit'); ?>"><i class="icon-edit icon-white"></i> Edit</a>
                <?php endif; ?>
                <?php if($this->isViewable('page_pickup_delete')): ?>
                <a class="btn btn-danger btn-mini" onclick="if(!confirm('Are you sure you want to delete the pickup <?php echo str_replace("'", "\'", $pickup['title']); ?>?')) { return false; } " href="<?php echo $this->url(array('pickup' => $pickup['id']), 'page_pickup_delete'); ?>"><i class="icon-trash icon-white"></i> Delete</a>
                <?php endif; ?>
            </div>
            <h4><?php echo $this->escape($pickup['title']); ?><?php echo (empty($pickup['map'])) ? '' : ' (<a href="' . $this->escape($pickup['map']) . '">Map</a>)'; ?></h4>
            <div><strong>When/Where:</strong> <?php echo $pickup['day']; ?> <?php echo $pickup['time']; ?> at <?php echo $pickup['location']; ?></div>
            <div><strong>Contact:</strong> <?php echo (empty($pickup['email'])) ? $this->fullname($pickup['user_id']) . ' ( ' . $this->generateEmailLink($pickup['user_id']) . ' )' : $this->generateEmailLink($pickup['email']); ?></div>
            <p><?php echo (empty($pickup['info'])) ? '&nbsp;' : $pickup['info']; ?></p>

            <hr/>
            <?php endforeach; ?>

            <h3>Disc Golf Locations</h3>

            <p>The PDGA manages a list of <a href="http://www.pdga.com/course_directory/zipcode?filter0=45201">locations</a> around Cincinnati.</p>
        </div>

        <div class="span3 page-links">
            <?php echo $this->partial('page-links.phtml', array('links' => $this->links, 'page' => $this->page)); ?>
        </div>
    </div>
</div>
