<form method="post">
    <div class="row">
        <dt>Year:</dt>
        <dd>
            <input id="tournament-year" type="text" name="year" value="<?php echo date('Y'); ?>"/>
        </dd>
    </div>
    <div class="row">
        <dt>Name:</dt>
        <dd>
            <input id="tournament-name" type="text" name="tournament" />
        </dd>
    </div>
    <div id="error-string"></div>
</form>
