<div id="page-banner" class="<?php echo $this->pageClass(); ?>">&nbsp;</div>
<div id="page-header" class="<?php echo $this->pageClass(); ?>">
    <span class="title">
        <h2><?php echo $this->escape($this->page->title); ?></h2>
    </span>
    <?php if(!$this->page->is_visible): ?>
    <div class="visible">
        *** This page is not yet visible to the public ***
    </div>
    <?php endif; ?>
    <span class="actions">
        <?php if($this->hasRole('admin')): ?>
        <a class="button" href="<?php echo $this->url(array('page' => $this->page->name), 'page_admin'); ?>">Admin</a>
        <?php endif; ?>
        <?php if($this->hasRole('admin') or $this->hasRole('editor') or $this->hasRole('editor', $this->page->id)): ?>
        <a class="button" href="<?php echo $this->url(array('page' => $this->page->name), 'page_edit'); ?>">Edit</a>
        <?php endif; ?>
    </span>
  
</div>

<div id="page-content" class="<?php echo $this->pageClass(); ?>">
    <?php echo $this->page->content; ?>
</div>
  
<?php echo $this->partial('page-links.phtml', array('links' => $this->links, 'page' => $this->page)); ?>
