<div id="page-banner" class="<?php echo $this->pageClass(); ?>">&nbsp;</div>

<div class="row actions">
    <div class="span9 pull-left <?php echo $this->pageClass(); ?>">
        <h2><?php echo $this->escape($this->page->title); ?></h2>
    </div>
    <div class="span2">
        <div class="btn-group pull-right">
            <?php if($this->isViewable('page_admin')): ?>
            <a class="btn btn-small" href="<?php echo $this->url(array('page' => $this->page->name), 'page_admin'); ?>"><i class="icon-book"></i> Admin</a>
            <?php endif; ?>
            <?php if($this->isViewable('page_edit')): ?>
            <a class="btn btn-small" href="<?php echo $this->url(array('page' => $this->page->name), 'page_edit'); ?>"><i class="icon-list"></i> Edit</a>
            <?php endif; ?>
        </div>
    </div>
</div>
<div class="page-content">
    <div class="row">
        <div class="span9">
            <?php echo $this->page->content; ?>
        </div>
        <div class="span3 page-links">
            <?php if($this->page->name == 'daytonultimate'): ?>
            <?php echo $this->partial('league-page-links.phtml', array('links' => $this->links, 'page' => $this->page)); ?>
            <?php else: ?>
            <?php echo $this->partial('page-links.phtml', array('links' => $this->links, 'page' => $this->page)); ?>
            <?php endif; ?>
        </div>
    </div>
</div>
