<h1>How to submit a bid</h1>

<?php if(1): //if($this->tournamentInfo->bid_due > date('Y-m-d H:i:s')): ?>
<p class="blurb">To submit a bid you must fill out this form with you and your team's information.  Please fill in all information so we can enter you into the correct spot for the tournament.  If you fail to enter in the correct information you risk being bumped by a team that fills out the information correctly.<p>

<p class="blurb">
    The cost for this tournament is <strong>$<?php echo $this->tournamentInfo->cost; ?></strong>, which you may pay upon successful bid submission with paypal.  If you have already submitted a bid and would just like to pay the tournament fee you may go <a href="<?php echo $this->url(array('name' => $this->tournament->name, 'year' => $this->tournament->year), 'tournament_bid_payment'); ?>">here</a> for payment information.
</p>
<div class="bid">
    <form method="post">
        <div class="team">
            <h2>Team Information:</h2>
            <?php echo $this->form->name; ?>
            <?php echo $this->form->city; ?>
            <?php echo $this->form->state; ?>
            <?php echo $this->form->division; ?>
        </div>
        <div class="contact">
            <h2 class="pad">Team Contact Information:</h2>
            <?php echo $this->form->contact_name; ?>
            <?php echo $this->form->contact_email; ?>
            <?php echo $this->form->contact_phone; ?>
        </div>
        <div class="comments">
            <h2 class="pad">Comments:</h2>
            <?php echo $this->form->comments; ?>
            <?php echo $this->form->bid; ?>
        </div>
    </form>
</div>
<?php elseif(empty($this->tournamentInfo->bid_due)): ?>
<p class="blurb">
    The bid submission has not been enabled yet.  Please check back at a later time.  You may contact the tournament director(s) <a href="">here</a>.
<p>

<?php else: ?>
<p class="blurb">
    The date to submit a bid has passed so you may not submit a bid.  If you want to contact the tournament director you may do so <a href="">here</a>.  If you have already submitted a bid and would like to pay for the tournament you may find more information about payments <a href="<?php echo $this->url(array('name' => $this->tournament->name, 'year' => $this->tournament->year), 'tournament_bid_payment'); ?>">here</a>.
<p>
<?php endif; ?>
