<div id="description">
    <div class="link">
        <?php if($this->isTournamentAdmin($this->tournament->id)): ?>
        <a href="<?php echo $this->url(array('name' => $this->tournament->name, 'year' => $this->tournament->year), 'tournament_home_edit'); ?>"><img src="<?php echo $this->baseUrl();?>/images/ico-edit.png" title="Edit Description"/></a>
        <?php endif; ?>
    </div>
    <?php echo $this->tournamentInfo->description; ?>
</div>

<div id="updates">
    <?php if($this->isTournamentAdmin($this->tournament->id)): ?>
    <div class="link">
        <a class="button" href="#">Add Update</a>
    </div>
    <?php endif; ?>
<?php foreach($this->updates as $update): ?>
    <div class="update">
        <div class="title">
            <?php echo $this->escape($update->title); ?>
            <?php if($this->isTournamentAdmin($this->tournament->id)): ?>
            <a href="#"><img src="<?php echo $this->baseUrl();?>/images/ico-delete.png" title="Delete Update"/></a>
            <?php endif; ?>
            <?php if($this->isTournamentAdmin($this->tournament->id)): ?>
            <a href="#"><img src="<?php echo $this->baseUrl();?>/images/ico-edit.png" title="Edit Update"/></a>
            <?php endif; ?>
        </div>
        <div class="when">Posted at: <?php echo $this->escape($update->posted); ?></div>
        <div class="info">
            <?php echo $update->content; ?>
        </div>
    </div>
<?php endforeach; ?>
</div>

