<h1>Location Information</h1>
<?php if($this->isTournamentAdmin($this->tournament->id)): ?>
<div class="page-actions">
    <a class="button" href="<?php echo $this->url(array('name' => $this->tournament->name, 'year' => $this->tournament->year), 'tournament_location_edit'); ?>">Edit Location Information</a>
</div>
<?php endif; ?>

<div class="map">
    <div class="title">
        <a target="_blank" href="<?php echo $this->generateMapSearchUrl($this->tournamentInfo); ?>" style="color:#0000FF;text-align:left"><?php echo $this->escape($this->tournamentInfo->location); ?></a>
    </div>
    <div class="address">
        <?php echo $this->escape($this->tournamentInfo->location_street); ?><br/>
        <?php echo $this->escape($this->tournamentInfo->location_city); ?>,
        <?php echo $this->escape($this->tournamentInfo->location_state); ?>
        <?php echo $this->escape($this->tournamentInfo->location_zip); ?>
    </div>

    <iframe width="725"
            height="450"
            frameborder="0"
            scrolling="no"
            marginheight="0"
            marginwidth="0"
            src="<?php echo $this->generateMapSearchUrl($this->tournamentInfo); ?>&amp;output=embed">
    </iframe>

</div>
