<h1>Lodging Information</h1>
<?php if($this->isTournamentAdmin($this->tournament->id)): ?>
<div class="page-actions">
    <a class="button" href="<?php echo $this->url(array('name' => $this->tournament->name, 'year' => $this->tournament->year), 'tournament_lodging_add'); ?>">Add Lodging Information</a>
</div>
<?php endif; ?>

<div class="map">
    <iframe width="425"
            height="450"
            frameborder="0"
            scrolling="no"
            marginheight="0"
            marginwidth="0"
            src="<?php echo $this->generateMapSearchUrl($this->tournamentInfo, true); ?>&amp;output=embed">
    </iframe>
    <a target="_blank" href="<?php echo $this->generateMapSearchUrl($this->tournamentInfo, true); ?>" style="color:#0000FF;text-align:left">Map in new window</a>
</div>

<div id="lodging">
    <?php foreach($this->lodging as $item): ?>
    <div class="item">
        <?php if($this->isTournamentAdmin($this->tournament->id)): ?>
        <div class="actions">
            <a href="<?php echo $this->url(array('name' => $this->tournament->name, 'year' => $this->tournament->year, 'lodging_id' => $item->id), 'tournament_lodging_edit'); ?>"><img src="<?php echo $this->baseUrl(); ?>/images/ico-edit.png" title="Edit Lodging"/></a>
            <a href="<?php echo $this->url(array('name' => $this->tournament->name, 'year' => $this->tournament->year, 'lodging_id' => $item->id), 'tournament_lodging_delete'); ?>"><img src="<?php echo $this->baseUrl(); ?>/images/ico-delete.png" title="Remove Lodging"/></a>
        </div>
        <?php endif; ?>
        <div class="title">
            <a href="<?php echo $this->escape($item->link); ?>"><?php echo $this->escape($item->title); ?></a>
        </div>
        <div class="street"><?php echo $this->escape($item->street); ?></div>
        <div class="city"><?php echo $this->escape($item->city . ', ' . $item->state . ' ' . $item->zip); ?></div>
        <div class="phone"><?php echo $this->escape($item->phone); ?></div>
        <div class="other"><?php echo $this->escape($item->other); ?></div>
    </div>
    <?php endforeach; ?>
</div>