<ul>
    <?php $active = ($this->section == 'home') ? ' class="active"' : ''; ?>
    <li><a<?php echo $active; ?> href="<?php echo $this->url(array('name' => $this->tournament->name, 'year' => $this->tournament->year), 'tournament_home'); ?>">Home</a></li>
    <?php $active = ($this->section == 'bid') ? ' class="active"' : ''; ?>
    <li><a<?php echo $active; ?> href="<?php echo $this->url(array('name' => $this->tournament->name, 'year' => $this->tournament->year), 'tournament_bid'); ?>">Bid Information</a></li>
    <?php $active = ($this->section == 'teams') ? ' class="active"' : ''; ?>
    <li><a<?php echo $active; ?> href="<?php echo $this->url(array('name' => $this->tournament->name, 'year' => $this->tournament->year), 'tournament_teams'); ?>">Teams</a></li>
    <?php $active = ($this->section == 'schedule') ? ' class="active"' : ''; ?>
    <li><a<?php echo $active; ?> href="<?php echo $this->url(array('name' => $this->tournament->name, 'year' => $this->tournament->year), 'tournament_schedule'); ?>">Schedule</a></li>
    <?php $active = ($this->section == 'location') ? ' class="active"' : ''; ?>
    <li><a<?php echo $active; ?> href="">Location</a></li>
    <?php $active = ($this->section == 'contact') ? ' class="active"' : ''; ?>
    <li><a<?php echo $active; ?> href="<?php echo $this->url(array('name' => $this->tournament->name, 'year' => $this->tournament->year), 'tournament_contact'); ?>">Contact</a></li>
</ul>
