<div class="span11 actions pull-right">
    <div class="btn-group pull-right">
        <?php if($this->isViewable('tournament_bid_edit')): ?>
        <a class="btn btn-small" href="<?php echo $this->url(array('name' => $this->tournament->name, 'year' => $this->tournament->year), 'tournament_bid_edit'); ?>"><i class="icon-book"></i> Edit Bid Information</a>
        <?php endif; ?>
    </div>
</div>
<div class="page-content">
    <div class="row">
        <div class="span12">
            <h2>Payment Information</h2>

            <?php if(!empty($this->tournamentInfo->paypal)): ?>
            <div class="well">
                <p>
                    If you would like to pay via paypal you may do so below.  Just click the button and it will take you to paypal's site to pay for the tournament.
                </p>
                <p>
                    The tournament cost is <span class="text-info">$<?php echo $this->escape($this->tournamentInfo->cost); ?></span>
                </p>
                <div class="center">
                    <?php if(count($this->teams)): ?>
                    <select id="team">
                        <option value="0">Select a Team</option>
                        <?php foreach($this->teams as $div => $teams): ?>
                        <optgroup label="<?php echo $this->escape($div); ?>">
                        <?php foreach($teams as $team): ?>
                            <option value="<?php echo $this->escape($team['id']); ?>"><?php echo $this->escape($team['name']); ?></option>
                        <?php endforeach; ?>
                        </optgroup>
                        <?php endforeach; ?>
                    </select><br/>
                    <a id="paypal-link" class="btn btn-success" onclick="return pay();" href="<?php echo $this->url(array('id' => $this->tournament->id, 'type' => 'tournament', 'user_id' => 0), 'paypal'); ?>">Pay via Paypal</a>
                    <?php else: ?>
                    <p><strong>There are currently no teams to pay for.</strong></p>
                    <?php endif; ?>
                </div>
            </div>
            <?php endif; ?>

            <div>
                <?php if(!empty($this->tournamentInfo->mail_payment)): ?>
                <p>
                    If you would like to mail a check in for the payment for the tournament you may mail payments to here:
                </p>
                <div>
                    <strong><pre><?php echo $this->escape($this->tournamentInfo->mail_payment); ?></pre></strong>
                </div>
                <?php endif; ?>

                <?php if(empty($this->tournamentInfo->mail_payment) and empty($this->tournamentInfo->paypal)): ?>
                <p>
                    The payment information for this tournament has not been setup yet.  Please check back at a later time when payment inforation will be put up.  If you have any questions you may email the tournament director or someone else associated with the tournament <a href="<?php echo $this->url(array('name' => $this->tournament->name, 'year' => $this->tournament->year), 'tournament_contact'); ?>">here</a>.
                </p>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

<script>
function pay()
{
    if($('#team').val() == 0) {
        alert('You must select a team to pay for.');
        return false;
    }

    var href = $('#paypal-link').prop('href');
    $('#paypal-link').prop('href', href + '/' + $('#team').val());
    return true;
}
</script>
