<div class="span11 actions pull-right">
    <div class="btn-group pull-right">
        <?php if($this->isTournamentAdmin($this->tournament->id)): ?>
        <a class="btn btn-small" href="<?php echo $this->url(array('name' => $this->tournament->name, 'year' => $this->tournament->year), 'tournament_teamadd'); ?>"><i class="icon-book"></i> Add Team</a>
        <?php endif; ?>
    </div>
</div>
<div class="page-content">
    <div class="row">
        <div class="span12">
            <h2>Current Teams</h2>

            <div class="tabbable">
                <ul class="nav nav-tabs">
                    <?php $i = 0; ?>
                    <?php foreach($this->teams as $division => $teams): ?>
                    <li<?php echo ($i == 0) ? ' class="active"' : ''; ?>><a data-toggle="tab" href="#<?php echo $this->escape(str_replace(' ', '', $division)); ?>"><?php echo $this->escape(ucwords($division)); ?> Division</a></li>
                    <?php $i++; ?>
                    <?php endforeach; ?>
                </ul>
                <div class="tab-content">
                    <?php $i = 0; ?>
                    <?php foreach($this->teams as $division => $teams): ?>
                    <div class="tab-pane<?php echo ($i == 0) ? ' active' : ''; ?>" id="<?php echo $this->escape(str_replace(' ', '', $division)); ?>">
                        <table class="table table-condensed table-hover">
                            <thead>
                                <tr>
                                    <th class="span5">Team</th>
                                    <th class="span3">Location</th>
                                    <th class="span1">Paid</th>
                                    <th class="span1">Accepted</th>
                                    <th class="span2">&nbsp;</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach($teams as $team): ?>
                                <tr>
                                    <td><?php echo $this->escape(ucwords($team['name'])); ?></td>
                                    <td><?php echo $this->escape($team['city']); ?>, <?php echo $this->escape($team['state']); ?></td>
                                    <td style="text-align: center;"><span class="<?php echo ($team['paid'] == 1) ? 'text-success' : 'text-error'; ?>"><?php echo ($team['paid'] == 1) ? 'Yes' : 'No'; ?></span></td>
                                    <td style="text-align: center;"><span class="<?php echo ($team['accepted'] == 1) ? 'text-success' : 'text-error'; ?>"><?php echo ($team['accepted'] == 1) ? 'Yes' : 'No'; ?></span></td>
                                    <td>
                                        <?php if($this->isTournamentAdmin($this->tournament->id)): ?>
                                        <a class="btn btn-mini btn-info" href="<?php echo $this->url(array('name' => $this->tournament->name, 'year' => $this->tournament->year, 'team_id' => $team['id']), 'tournament_teamedit'); ?>"><i class="icon-edit icon-white"></i> Edit</a>
                                        <a class="btn btn-mini btn-danger" onclick="return confirm('Are you sure you want to delete this team?');" href="<?php echo $this->url(array('name' => $this->tournament->name, 'year' => $this->tournament->year, 'team_id' => $team['id']), 'tournament_teamdelete'); ?>"><i class="icon-trash icon-white"></i> Remove</a>
                                        <?php endif; ?>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                    <?php $i++; ?>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
</div>
