<ul>
    <?php if($this->user): ?>
    <li><a id="logout-link" href="#">LOGOUT</a></li>
    <?php else: ?>
    <li><a id="login-link" href="#">LOGIN / REGISTER</a></li>
    <?php endif; ?>
    <li><a href="<?php echo $this->url(array(), 'page_contact'); ?>">CONTACT US</a> |</li>
    <?php if($this->isTournamentAdmin($this->tournament->id)): ?>
    <li><a href="<?php echo $this->url(array('name' => $this->tournament->name, 'year' => $this->tournament->year), 'tournament_admin'); ?>">ADMIN</a> |</li>
    <?php endif; ?>
    <li><a href="<?php echo $this->baseUrl(); ?>">CUPA HOME</a> |</li>
</ul>
