<ul>
    <?php if($this->user): ?>
    <li><a id="logout-link" href="#">LOGOUT</a></li>
    <?php else: ?>
    <li class="dropdown">
        <a id="login-dropdown-link" href="#" class="dropdown-toggle" data-toggle="dropdown">
            LOGIN
        </a>
        <ul class="dropdown-menu pull-right">
            <li class="span5">
                <form id="login-form">
                    <div id="login-error"></div>
                    <label for="username" >Username/Email</label>
                    <input id="username" class="span4" type="text" name="username" />
                    <label for="password">Password</label>
                    <input id="password" class="span4" type="password" name="password" />
                    <div class="row">
                        <div class="span1">
                            <a id="login-link" href="#" class="btn btn-primary">Login</a>
                        </div>
                        <div class="span3">
                            <div class="btn-group row btn-group-vertical pull-right">
                                <a href="<?php echo $this->url(array(), 'auth_forgot_password') ?>" class="btn">Forgot Password?</a>
                                <a href="<?php echo $this->url(array(), 'auth_registration') ?>" class="btn">Register</a>
                            </div>
                        </div>
                    </div>
                </form>
            </li>
        </ul>
    </li>
    <?php endif; ?>
    <li><a href="<?php echo $this->url(array(), 'page_contact'); ?>">CONTACT US</a> |</li>
    <?php if($this->isViewable('tournament_admin')): ?>
    <li><a href="<?php echo $this->url(array('name' => $this->tournament->name, 'year' => $this->tournament->year), 'tournament_admin'); ?>">ADMIN</a> |</li>
    <?php endif; ?>
    <li><a href="<?php echo $this->baseUrl(); ?>/">CUPA HOME</a> |</li>
</ul>
