<form id="login-form" method="post">
    <div class="login-row">
    <?php echo $this->form->getElement('username'); ?>
    </div>

    <div class="login-row">
    <?php echo $this->form->getElement('password'); ?>
    </div>

    <div class="login-left-cel">
        <input id="login-submit" type="submit" value="Login"/>
    </div>

    <div class="login-right-cel">
        Don't have an account?<br/>
        <a href="#">Sign Up</a>
    </div>
    
    <div class="login-row">
        <a href="#">Forgot Username?</a> |
        <a href="#">Forgot Password?</a>
    </div>

</form>