<form id="login-form" method="post">
    <div id="error" class="login-row">&nbsp;</div>
            
    <div class="login-row">
        <?php echo $this->form->getElement('username'); ?>
    </div>

    <div class="login-row">
        <?php echo $this->form->getElement('password'); ?>
    </div>

    <div class="login-left-cel">
        <input class="button" id="login-submit" type="submit" value="Login"/>
    </div>

    <div class="login-right-cel">
        Don't have an account?<br/>
        <a href="<?php echo $this->url(array(), 'auth_registration') ?>">Register Here</a>
    </div>
    
    <div class="login-row">
        <a href="<?php echo $this->url(array(), 'auth_password_reset') ?>">Forgot Username?</a> |
        <a href="<?php echo $this->url(array(), 'auth_password_reset') ?>">Forgot Password?</a>
    </div>

</form>