<div id="page-banner">&nbsp;</div>

<div class="row">
    <div class="offset1 span10">
        <p>
            Please enter the email address you used to request an password reset.
            This is to further confirm you are who we think you are.  Also enter in the password you
            would like to use from now on for the system.  If you have any questions or problems please
            <a href="<?php echo $this->url(array(), 'page_contact'); ?>">contact the webmaster</a>.
        </p>
    </div>
    <div class="offset1 span10">
        <?php echo $this->form; ?>
    </div>
</div>
