<div id="page-links" class="<?php echo $this->pageClass(); ?>">
    <ul>
        <?php foreach($this->links as $link): ?>
        <?php if($link['name'] == substr($this->page->name, -7)): ?>
        <li><?php echo $this->escape($link['title']); ?></li>
        <?php else: ?>
        <li><a href="<?php echo $this->url(array('type' => $link['name']), 'leagues_view');?>"><?php echo $this->escape($link['title']); ?></a></li>
        <?php endif; ?>
        <?php endforeach; ?>
        <li><a href="<?php echo $this->url(array(), 'page_forms');?>">Waivers & Forms</a></li>
    </ul>
</div>