<ul>
    <li><a class="about" href="<?php echo $this->url(array('page' => 'about'), 'page_view'); ?>">About Us</a></li>
    <li><a class="youth" href="<?php echo $this->url(array('page' => 'youth'), 'page_view'); ?>">Youth Ultimate</a></li>
    <li><a class="leagues" href="<?php echo $this->url(array('page' => 'leagues'), 'page_view'); ?>">Leagues</a></li>
    <li><a class="pickup" href="<?php echo $this->url(array('page' => 'pickup'), 'page_view'); ?>">Tournaments & Pickup</a></li>
    <li><a class="clubs" href="<?php echo $this->url(array('page' => 'clubs'), 'page_view'); ?>">Area Club Teams</a></li>
    <li><a class="links" href="<?php echo $this->url(array('page' => 'links'), 'page_view'); ?>">Resources & Links</a></li>
</ul>