<ul>
    <!-- <li><a href="<?php echo $this->url(array(), 'volunteer'); ?>">VOLUNTEER INFO</a> |</li> -->
    <?php if($this->hasRole('admin')): ?>
    <li><a href="<?php echo $this->url(array(), 'admin'); ?>">ADMIN</a> |</li>
    <?php endif; ?>
    <?php if($this->hasRole('manager') or $this->hasRole('admin') or $this->isLeagueDirector()): ?>
    <li><a href="<?php echo $this->url(array(), 'manage'); ?>">MANAGE</a> |</li>
    <?php endif; ?>
    <li><a href="<?php echo $this->url(array(), 'page_contact'); ?>">CONTACT US</a> |</li>
    <?php if($this->user): ?>
    <li><a href="<?php echo $this->url(array(), 'profile'); ?>">MY PROFILE</a> |</li>
    <?php if($this->isImpersonated): ?>
    <li><a id="logout-link" href="#">STOP IMPERSONATING <?php echo strtoupper($this->user->username); ?></a></li>
    <?php else: ?>
    <li><a id="logout-link" href="#">LOGOUT</a></li>
    <?php endif; ?>
    <?php else: ?>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            LOGIN
        </a>
        <ul class="dropdown-menu pull-right">
            <li class="span4">
                <form>
                    <div id="login-error"></div>
                    <label for="username" >Username/Email</label>
                    <input id="username" class="span4" type="text" name="username" />
                    <label for="password">Password</label>
                    <input id="password" class="span4" type="password" name="password" />
                    <div class="row">
                        <div class="span1">
                            <a id="login-link" href="#" class="btn btn-primary">Login</a>
                        </div>
                        <div class="span3">
                            <div class="btn-group row btn-group-vertical pull-right">
                                <a href="<?php echo $this->url(array(), 'auth_forgot_password') ?>" class="btn">Forgot Password</a>
                                <a href="<?php echo $this->url(array(), 'auth_registration') ?>" class="btn">Register</a>
                            </div>
                        </div>
                    </div>
                </form>
            </li>
        </ul>
    </li>
    <?php endif; ?>
</ul>
