<ul>
    <?php if($this->hasRole('admin') and isset($this->tournament->id)): ?>
    <li><a href="<?php echo $this->url(array('name' => $this->tournament->name, 'year' => $this->tournament->year), 'tournament_admin'); ?>">ADMIN</a> |</li>
    <?php elseif($this->hasRole('admin')): ?>
    <li><a href="">ADMIN</a> |</li>
    <?php endif; ?>
    <li><a href="<?php echo $this->url(array(), 'page_contact'); ?>">CONTACT US</a> |</li>
    <?php if($this->user): ?>
    <li><a href="<?php echo $this->url(array(), 'profile'); ?>">MY PROFILE</a> |</li>
    <?php if($this->isImpersonated): ?>
    <li><a id="logout-link" href="#">STOP IMPERSONATING <?php echo strtoupper($this->user->username); ?></a></li>
    <?php else: ?>
    <li><a id="logout-link" href="#">LOGOUT</a></li>
    <?php endif; ?>
    <?php else: ?>
    <li><a id="login-link" href="#">LOGIN / REGISTER</a></li>
    <?php endif; ?>
</ul>
