<div id="page-banner" class="about">&nbsp;</div>

<div class="row actions">
    <div class="span9 pull-left about">
        <h2>CUPA Volunteer Corps</h2>
    </div>
    <div class="span2">
        <div class="btn-group pull-right">
            <?php if($this->isViewable('volunteer_opportunity_add')): ?>
            <a class="btn btn-small" href="<?php echo $this->url(array(), 'volunteer_opportunity_add'); ?>"><i class="icon-book"></i> Add Opportunity</a>
            <?php endif; ?>
        </div>
    </div>
</div>
<div class="page-content">
    <div class="row">
        <div class="span9">
            <br/>
            <p>
                Established in 2012, the <strong>Cincinnati Ultimate Players Association (CUPA)'s Volunteer Corps</strong>
                aids in the coordination of all volunteer-run events, upholding CUPA’s mission of serving as a regional
                resource, promoting growth in the sport of ultimate and instilling Spirit of the Game&trade; at all levels
                of play.
            </p>
            <br/>
            <p>
                Both upcoming and past volunteering opportunities are available for you (or any of your friends) after the
                following form is completed. Please complete the following <a href="<?php echo $this->url(array(), 'volunteer_register'); ?>">form</a> so we can best position
                you with an event you would enjoy being a part of, while helping CUPA serve others in our community.
            </p>
            <br/>
            <p>
                If you have any questions, please email <a href="&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#118;&#111;&#108;&#117;&#110;&#116;&#101;&#101;&#114;&#64;&#99;&#105;&#110;&#99;&#121;&#117;&#108;&#116;&#105;&#109;&#97;&#116;&#101;&#46;&#111;&#114;&#103;">&#118;&#111;&#108;&#117;&#110;&#116;&#101;&#101;&#114;&#64;&#99;&#105;&#110;&#99;&#121;&#117;&#108;&#116;&#105;&#109;&#97;&#116;&#101;&#46;&#111;&#114;&#103;</a>
            </p>
        </div>
        <div class="span3 page-links">
            <?php echo $this->partial('volunteer/links.phtml'); ?>
        </div>
    </div>
</div>
