<div id="page-banner">&nbsp;</div>
<div id="page-header">&nbsp;</div>

<div id="page-content" class="about">
    <h1>About CUPA Volunteer Corps</h1>

    <p class="indented">
        Established in 2012, the <strong>Cincinnati Ultimate Players Association (CUPA)'s Volunteer Corps</strong>
        aids in the coordination of all volunteer-run events, upholding CUPA’s mission of serving as a regional
        resource, promoting growth in the sport of ultimate and instilling Spirit of the Game&trade; at all levels
        of play.
    </p>
    <p class="indented">
        Both upcoming and past volunteering opportunities are available for you (or any of your friends) after the
        following form is completed. Please complete the following <a href="<?php echo $this->url(array(), 'volunteer_signup'); ?>">form</a> so we can best position
        you with an event you would enjoy being a part of, while helping CUPA serve others in our community.
    </p>
    <p class="indented">
        If you have any questions, please email <a href="&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#118;&#111;&#108;&#117;&#110;&#116;&#101;&#101;&#114;&#64;&#99;&#105;&#110;&#99;&#121;&#117;&#108;&#116;&#105;&#109;&#97;&#116;&#101;&#46;&#111;&#114;&#103;">&#118;&#111;&#108;&#117;&#110;&#116;&#101;&#101;&#114;&#64;&#99;&#105;&#110;&#99;&#121;&#117;&#108;&#116;&#105;&#109;&#97;&#116;&#101;&#46;&#111;&#114;&#103;</a>
    </p>
</div>

<?php echo $this->partial('volunteer/links.phtml'); ?>
