<div id="page-banner" class="about">&nbsp;</div>

<div class="row actions">
    <div class="span9 about">
        <h2>Volunteer Opportunities</h2>
    </div>
    <div class="span2">
        <div class="btn-group pull-right">
            <?php if($this->isViewable('volunteer_opportunity_add')): ?>
            <a class="btn btn-small" href="<?php echo $this->url(array(), 'volunteer_opportunity_add'); ?>"><i class="icon-book"></i> Add Opportunity</a>
            <?php endif; ?>
        </div>
    </div>
</div>
<div class="page-content">
    <div class="row">
        <div class="span9">
            <?php if(count($this->volunteers)): ?>

            <?php foreach($this->volunteers as $volunteer): ?>
            <div>
                <div class="pull-right btn-group">
                    <?php if($this->isViewable('volunteer_signup')): ?>
                    <a class="btn btn-mini" href="<?php echo $this->url(array('volunteer_id' => $volunteer['id']), 'volunteer_signup'); ?>"><i class="icon-th-list"></i> Sign-up</a>
                    <?php endif; ?>
                    <?php if($this->isViewable('volunteer_list_members')): ?>
                    <a class="btn btn-mini" href="<?php echo $this->url(array('volunteer_id' => $volunteer['id']), 'volunteer_list_members'); ?>"><i class="icon-list"></i> Volunteers</a>
                    <?php endif; ?>
                    <?php if($this->isViewable('volunteer_opportunity_edit')): ?>
                    <a class="btn btn-mini btn-info" href="<?php echo $this->url(array('volunteer_id' => $volunteer['id']), 'volunteer_opportunity_edit'); ?>"><i class="icon-edit icon-white"></i> Edit</a>
                    <?php endif; ?>
                    <?php if($this->isViewable('volunteer_opportunity_remove')): ?>
                    <a class="btn btn-mini btn-danger" onclick="return confirm('Are you sure you want to delete this?');" href="<?php echo $this->url(array('volunteer_id' => $volunteer['id']), 'volunteer_opportunity_remove'); ?>"><i class="icon-trash icon-white"></i> Remove</a>
                    <?php endif; ?>
                </div>
                <h2 class="offset1 text-error"><?php echo $this->escape($volunteer['name']); ?></h2>
                <em class="offset1 muted">
                <?php if(date('Y-m-d', strtotime($volunteer['start'])) == date('Y-m-d', strtotime($volunteer['end']))): ?>
                    <?php echo $this->escape(date('m/d/Y', strtotime($volunteer['start']))); ?> <?php echo $this->escape(date('h:i A', strtotime($volunteer['start']))); ?> - <?php echo $this->escape(date('h:i A', strtotime($volunteer['end']))); ?>
                    <?php else: ?>
                    <?php echo $this->escape(date('m/d/Y @ h:i A', strtotime($volunteer['start']))); ?> to <?php echo $this->escape(date('m/d/Y @ h:i A', strtotime($volunteer['end']))); ?>
                <?php endif; ?>
                </em>
                <div>
                    <dl class="dl-horizontal">
                        <dt>Location</dt>
                        <dd><a target="blank" href="<?php echo $this->generateVolunteerMap($volunteer); ?>"><?php echo $this->escape($volunteer['location_name']) . '</a><br/>' . $this->escape($volunteer['address']) . '<br/>' . $this->escape($volunteer['city'] . ', ' . $volunteer['state'] . ' ' . $volunteer['zip']); ?><br/><br/></dd>
                        <dt>Volunteers Needed</dt>
                        <dd><strong class="text-info"><?php echo $this->escape($volunteer['max_volunteers'] - count($volunteer['members'])); ?></strong> More Volunteers Needed</dd>
                        <dt>Contact:</dt>
                        <dd><?php echo $this->generateEmailLink($volunteer['contact']->email, $volunteer['contact']->first_name . ' ' . $volunteer['contact']->last_name); ?></dd>
                        <dt>About the Event:</dt>
                        <dd><?php echo $volunteer['information']; ?></dd>
                    </dl>
                </div>
            </div>
            <hr/>
            <?php endforeach; ?>
            <?php else: ?>
            <h3>There are no opportunities currently available, please check back at a later time.</h3>
            <?php endif; ?>
        </div>
        <div class="span3 page-links">
            <?php echo $this->partial('volunteer/links.phtml'); ?>
        </div>
    </div>
</div>
