<div id="page-banner" class="about">&nbsp;</div>

<div class="row actions">
    <div class="span9 about">
        <h2>Volunteer Opportunities</h2>
    </div>
    <div class="span2">
        <div class="btn-group pull-right">
            <?php if($this->isVolunteerAdmin()): ?>
            <a class="btn btn-small" href="<?php echo $this->url(array(), 'volunteer_opportunity_add'); ?>"><i class="icon-book"></i> Add Opportunity</a>
            <?php endif; ?>
        </div>
    </div>
</div>
<div class="page-content">
    <div class="row">
        <div class="span9">
            <?php foreach($this->volunteers as $volunteer): ?>
            <div>
                <div class="pull-right btn-group">
                    <a class="btn btn-mini"><i class="icon-th-list"></i> Sign-up</a>
                    <?php if($this->isVolunteerAdmin($volunteer['id'])): ?>
                    <a class="btn btn-mini btn-info" href="#"><i class="icon-edit icon-white"></i> Edit</a>
                    <a class="btn btn-mini btn-danger" onclick="return confirm('Are you sure you want to delete this?');" href="#"><i class="icon-trash icon-white"></i> Remove</a>
                    <?php endif; ?>
                </div>
                <h2 class="offset1 text-error"><?php echo $this->escape($volunteer['name']); ?></h2>
                <em class="offset1 muted">
                <?php if(date('Y-m-d', strtotime($volunteer['start'])) == date('Y-m-d', strtotime($volunteer['end']))): ?>
                    <?php echo $this->escape(date('m/d/Y', strtotime($volunteer['start']))); ?> <?php echo $this->escape(date('h:i A', strtotime($volunteer['start']))); ?> - <?php echo $this->escape(date('h:i A', strtotime($volunteer['end']))); ?>
                    <?php else: ?>
                    <?php echo $this->escape(date('m/d/Y @ h:i A', strtotime($volunteer['start']))); ?> to <?php echo $this->escape(date('m/d/Y @ h:i A', strtotime($volunteer['end']))); ?>
                <?php endif; ?>
                </em>
                <div>

                    <dl class="dl-horizontal">
                        <dt>Location</dt>
                        <dd><?php echo $this->escape($volunteer['location']) . '<br/>' . $this->escape($volunteer['street']) . '<br/>' . $this->escape($volunteer['city'] . ', ' . $volunteer['state'] . ' ' . $volunteer['zip']); ?><br/><br/></dd>
                        <dt>Volunteers Needed</dt>
                        <dd><strong class="text-info"><?php echo $this->escape($volunteer['max_volunteers'] - count($volunteer['members'])); ?></strong> More Volunteers Needed</dd>
                        <dt>About the Event:</dt>
                        <dd><?php echo $volunteer['information']; ?></dd>
                    </dl>
                </div>
            </div>
            <hr/>
            <?php endforeach; ?>
        </div>
        <div class="span3 page-links">
            <?php echo $this->partial('volunteer/links.phtml'); ?>
        </div>
    </div>
</div>
