<div id="page-banner" class="about">&nbsp;</div>

<div class="row actions">
    <div class="span9 pull-left about">
        <h2>CUPA Volunteer Corps Pool</h2>
    </div>
    <div class="span2">
        <div class="btn-group pull-right">
            <?php if($this->isViewable('volunteer_opportunity_add')): ?>
            <a class="btn btn-small" href="<?php echo $this->url(array(), 'volunteer_opportunity_add'); ?>"><i class="icon-book"></i> Add Opportunity</a>
            <?php endif; ?>
            <a class="btn btn-small" href="<?php echo $this->url(); ?>?export=1"><i class="icon-list"></i> Export List</a>
        </div>
    </div>
</div>
<div class="page-content">
    <div class="row">
        <div class="span9">
            <?php if(count($this->volunteers) > 0): ?>
            <table class="table table-condensed table-hover">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->volunteers as $volunteer): ?>
                    <tr>
                        <td><?php echo $this->escape($volunteer['volunteer_name']); ?></td>
                        <td><?php echo (empty($volunteer['email'])) ? $this->escape($volunteer['parent_email']) : $this->escape($volunteer['email']); ?></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <?php echo $this->paginationControl($this->volunteers,
                                    'Sliding',
                                    'admin/pagination.phtml'); ?>
            <?php else: ?>
            <p>There are no volunteers in the system right now.</p>
            <?php endif; ?>
        </div>
        <div class="span3 page-links">
            <?php echo $this->partial('volunteer/links.phtml'); ?>
        </div>
    </div>
</div>
