<div id="page-banner" class="about">&nbsp;</div>

<div class="row actions">
    <div class="span9 pull-left about">
        <h2>Become a Volunteer</h2>
    </div>
    <div class="span2">
        <div class="btn-group pull-right">
        </div>
    </div>
</div>
<div class="page-content">
    <div class="row">
        <div class="span9">
            <br/>
            <?php echo $this->form; ?>
        </div>
        <div class="span3 page-links">
            <?php echo $this->partial('volunteer/links.phtml'); ?>
        </div>
    </div>
</div>
