<div id="page-banner" class="about">&nbsp;</div>

<div class="row actions">
    <div class="span9 pull-left about">
        <h2>Become a Volunteer</h2>
    </div>
    <div class="span2">
        <div class="btn-group pull-right">
        </div>
    </div>
</div>
<div class="page-content">
    <div class="row">
        <div class="span9">
            <div class="hero-unit">
                <h2>Thank You!</h2>
                <p>
                    You have already registered to be a volunteer.  You should be hearing from us via email
                    for upcoming opportunities, you may also click the `View Opportunities` link to view the
                    upcoming opportunities.
                </p>
            </div>
        </div>
        <div class="span3 page-links">
            <?php echo $this->partial('volunteer/links.phtml'); ?>
        </div>
    </div>
</div>
