<!DOCTYPE html>
<html>
    <head>
        <title>CUPA - Cincinnati Ultimate Player Association</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=9; IE=8; IE=7; IE=EDGE" />
        <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/error/style.css" type="text/css" media="all" />
    </head>
    <body>
        <header><img src="<?php echo $this->baseUrl(); ?>/images/cupa.png" width="221" height="80"/></header>
        <?php echo $this->layout()->content; ?>
    </body>
</html>
