<!DOCTYPE html>
<html>
	<head>
	<title>CUPA - Cincinnati Ultimate Players Association</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.1.0-rc.1/jquery.mobile-1.1.0-rc.1.min.css" />
	<script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
	<script src="http://code.jquery.com/mobile/1.1.0-rc.1/jquery.mobile-1.1.0-rc.1.min.js"></script>
</head>
<body>
    <div data-role="page">
        <div data-role="header">
            <h1>CUPA News</h1>
        </div><!-- /header -->
        <div data-role="content">
            <?php echo $this->partial('menu.phtml', array('user' => $this->user)); ?>
            <?php echo $this->layout()->content; ?>
        </div>
        </div><!-- /content -->
    </div><!-- /page -->
</body>
</html>