<!DOCTYPE html>
<html>
    <head>
        <title>CUPA - Cincinnati Ultimate Player Association</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=0" />
        <?php if(APPLICATION_ENV != 'production' and APPLICATION_ENV != 'testing'): ?>
        <meta http-equiv="EXPIRES" content="0" />
        <?php endif; ?>
        <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/tournament.css" type="text/css" media="all" />
        <?php echo $this->headLink() . "\n"; ?>
        <?php $this->headScript()->prependFile($this->baseUrl() . '/js/jquery-ui-1.8.16.min.js') . "\n"; ?>
        <?php $this->headScript()->appendFile($this->baseUrl() . '/js/global.js') . "\n"; ?>
        <?php echo $this->headScript()->prependFile($this->baseUrl() . '/js/jquery-1.7.1.min.js') . "\n"; ?>
        <script>
            var BASE_URL = '<?php echo $this->baseUrl(); ?>';
        </script>
        <link rel="shortcut icon" href="<?php echo $this->baseUrl(); ?>/favicon.ico" />
    </head>
    <body>
        <header>
            <div class="title">
                <?php echo $this->tournament->display_name; ?>
            </div>
            <div class="when">
                <?php if(isset($this->tournamentInfo->start)): ?>
                <?php echo date('l F jS Y', strtotime($this->tournamentInfo->start)); ?>
                <?php else: ?>
                <?php echo 'TBD'; ?>
                <?php endif; ?>
            </div>
            <div class="menu">
                <?php echo $this->partial('tournament/top-menu.phtml', array('user' => $this->user, 'isImpersonated' => $this->isImpersonated, 'tournament' => $this->tournament)); ?>
                <div id="login-container">Login Container</div>
            </div>
        </header>
        <nav>
            <?php echo $this->partial('tournament/menu.phtml', array('user' => $this->user, 'tournament' => $this->tournament, 'section' => $this->section)); ?>
        </nav>
        <?php echo $this->message(); ?>
        <div id="main-content">
            <?php echo $this->layout()->content; ?>
            <div class="clearfix"></div>
        </div>
        <footer>
            &copy;<?php echo date('Y'); ?> Cincinnati Ultimate Players Association<br/>
            If you have any difficulties while visiting our site, please contact: <a href="<?php echo $this->url(array(), 'page_contact');?>">CUPA</a>
        </footer>
    </body>
</html>
<?php if(!empty($this->headerImage)): ?>
<script>
    $('header').css('background-image', "url('<?php echo $this->headerImage; ?>')");
</script>
<?php endif; ?>