<!DOCTYPE html>
<html>
    <head>
        <title>CUPA - Cincinnati Ultimate Player Association</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=9; IE=8; IE=7; IE=EDGE" />
        <?php if(APPLICATION_ENV != 'production' and APPLICATION_ENV != 'testing'): ?>
        <meta http-equiv="EXPIRES" content="0" />
        <?php endif; ?>
        <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/ie-fix.css" type="text/css" media="all" />
        <![endif]-->
        <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/bootstrap.min.css" type="text/css" media="all" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/tournament.css" type="text/css" media="all" />
        <?php echo $this->headLink() . "\n"; ?>
        <link rel="shortcut icon" href="<?php echo $this->baseUrl(); ?>/favicon.ico" />
        <style>
            header {
                background-image: url('<?php echo $this->getTournamentHeaderImage(); ?>');
            }
        </style>
    </head>
    <body>
        <header>
            <div class="title">
                <?php echo $this->tournament->display_name; ?>
            </div>
            <div class="when">
                <?php if(isset($this->tournamentInfo->start)): ?>
                <?php echo date('l, F j, Y', strtotime($this->tournamentInfo->start)); ?>
                <?php else: ?>
                <?php echo 'TBD'; ?>
                <?php endif; ?>
            </div>
            <div class="menu">
                <?php echo $this->partial('tournament/top-menu.phtml', array('user' => $this->user, 'isImpersonated' => $this->isImpersonated, 'tournament' => $this->tournament)); ?>
            </div>
        </header>
        <nav>
            <?php echo $this->partial('tournament/menu.phtml', array('user' => $this->user, 'tournament' => $this->tournament, 'section' => $this->section)); ?>
        </nav>
        <div id="main-content">
            <?php echo $this->message(); ?>
            <?php echo $this->layout()->content; ?>
        </div>
        <footer>
            <!--Hosted by: InMotion Hosting<br/> -->
            &copy;<?php echo date('Y'); ?> Cincinnati Ultimate Players Association<br/>
            If you have any difficulties while visiting our site, please contact: <a href="<?php echo $this->url(array(), 'page_contact');?>">CUPA</a>
        </footer>
        <script>
            var BASE_URL = '<?php echo $this->baseUrl(); ?>';
        </script>
        <?php echo $this->headScript()
                        ->prependFile($this->baseUrl() . '/js/global.js')
                        ->prependFile($this->baseUrl() . '/js/bootstrap.min.js')
                        ->prependFile($this->baseUrl() . '/js/jquery-1.9.0.min.js') . "\n"; ?>
    </body>
</html>
