<div id="page-banner"></div>
<div class="row">
    <div class="offset1 span10">
        <h1 style="text-align: center;"><?php echo $this->escape($this->year); ?> <?php echo $this->escape($this->club->name); ?> Roster</h1>
        <div class="pull-right">
        	<a class="btn btn-small" href="<?php echo $this->url(array('club_id' => $this->club->id, 'year' => $this->year), 'club_home'); ?>"><i class="icon-arrow-left"></i> Back</a>
        </div>
    </div>
</div>
<div class="row">
    <div class="offset3 span6"  style="text-align: center;">
    	<?php echo $this->form; ?>
    </div>
</div>
<br/><br/>
<div class="row">
    <div class="offset1 span10"  style="text-align: center;">
    	<table class="table table-condensed table-hover">
			<thead>
				<tr>
					<th>Name</th>
					<th class="span2">Actions</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach($this->members as $member): ?>
				<tr>
					<td><?php echo $this->escape($member['member']); ?></td>
					<td align="center">
                        <?php if($this->isViewable('club_member_remove')): ?>
						<a class="btn btn-mini btn-danger" onclick="if(!confirm('Are you sure you want to remove this member?')) { return false; }" href="<?php echo $this->url(array('club_id' => $this->club->id, 'id' => $member['id']), 'club_member_remove'); ?>"><i class="icon-trash icon-white"></i> Remove</a>
                        <?php endif; ?>
					</td>
				</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
    </div>
</div>
