<h1><?php echo $this->escape($this->year . ' ' . $this->club->name . ' Roster'); ?></h1>

<div class="action">
	<a class="button" href="<?php echo $this->url(array('club_id' => $this->club->id), 'club_home'); ?>#<?php echo $this->escape($this->year); ?>">Back</a>
</div>
<div class="add-member">
	<?php echo $this->form; ?>
	<div class="clearfix">&nbsp;<br/>&nbsp;</div>
</div>

<div class="view-members">
	<table>
		<thead>
			<tr>
				<th width="300px">Name</th>
				<th width="100px">Actions</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($this->members as $member): ?>
			<tr>
				<td><?php echo $this->escape($member['member']); ?></td>
				<td align="center">
					<a title="Remove Player" onclick="if(!confirm('Are you sure you want to remove this member?')) { return false; }" href="<?php echo $this->url(array('id' => $member['id']), 'club_member_remove'); ?>"><img src="<?php echo $this->baseUrl(); ?>/images/ico-delete.png"/></a>
				</td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>
<div class="action">
	<a class="button" href="<?php echo $this->url(array('club_id' => $this->club->id), 'club_home'); ?>#<?php echo $this->escape($this->year); ?>">Back</a>
</div>
