<div id="page-banner"></div>
<div class="row">
    <div class="offset1 span10">
        <h1 style="text-align: center;">
            <?php echo $this->escape($this->club->name); ?><br/>
            <small>A <?php echo $this->escape($this->club->type); ?> Ultimate Team from <?php echo $this->escape($this->club->begin); ?><?php echo $this->escape((empty($this->club->end)) ? '' : $this->club->end); ?></small>
        </h1>
    </div>
</div>
<div class="row">
    <div class="offset1 span10"  style="text-align: center;">
        <?php if($this->club->facebook): ?>
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
        <div class="fb-like" data-href="http://www.facebook.com/<?php echo $this->escape($this->club->facebook); ?>" data-send="false" data-layout="button_count" data-width="100" data-show-faces="false"></div>
        <?php endif; ?>
        <?php if($this->club->twitter): ?>
        <a href="https://twitter.com/<?php echo $this->escape($this->club->twitter); ?>" class="twitter-follow-button" data-show-count="false" data-dnt="true">Follow @cincysfb</a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
        <?php endif; ?>
        <br/><br/>
    </div>
</div>
<div class="row">
    <div class="offset1 span10" style="text-align: center;">
        <strong>Captains:</strong> <?php echo (strlen($this->getClubCaptains($this->club->id)) > 0) ? $this->getClubCaptains($this->club->id) . '<br/>' : 'Unknown<br/>'; ?>
        <?php echo (empty($this->club->website)) ? '&nbsp;' : '<strong>Website:</strong> <a class="website-link" href="' . $this->escape($this->club->website) . '">' . $this->escape($this->club->website) . '</a><br/>'; ?>
        <?php if($this->club->email != null): ?><strong>Contact Email:</strong> <?php echo $this->generateEmailLink($this->club->email); ?><?php endif; ?>
    </div>
</div>
<div class="row">
    <div class="offset2 span8" style="text-align: justify;">
        <p><?php echo $this->club->content; ?></p>
    </div>
</div>
<div class="row">
    <div class="offset1 span10" style="text-align: justify;">
        <ul class="nav nav-tabs">
            <?php $i = 0; ?>
            <?php foreach($this->years as $year => $members): ?>
            <li<?php echo ($i == 0) ? ' class="active"' : ''; ?>><a href="#<?php echo $this->escape($year); ?>" data-toggle="tab"><?php echo $this->escape($year); ?></a></li>
            <?php $i++; ?>
            <?php endforeach; ?>
        </ul>
        <div class="tab-content">
            <?php $i = 0; ?>
            <?php foreach($this->years as $year => $members): ?>
            <div class="tab-pane<?php echo ($i == 0) ? ' active' : ''; ?>" id="<?php echo $this->escape($year); ?>">
                <div class="pull-right">
                    <a class="btn btn-info" href="<?php echo $this->url(array('club_id' => $this->club->id, 'year' => $year), 'club_edit'); ?>"><i class="icon-edit icon-white"></i> Edit Roster</a>
                </div>
                <ul class="nav well">
                    <?php foreach($members as $member): ?>
                    <li><a href="<?php echo $this->url(array('user_id' => $member['user_id']), 'page_profile_public'); ?>"><h4><?php echo $this->escape($member['member']); ?></h4></a></li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <?php $i++; ?>
            <?php endforeach; ?>
        </div>
    </div>
</div>
