<?php if(APPLICATION_ENV == 'development'): ?>
  <h1>An error occurred</h1>
  <h2><?php echo $this->message ?></h2>

  <?php if (isset($this->exception)): ?>

  <h3>Exception information:</h3>
  <p>
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
  </p>

  <h3>Stack trace:</h3>
  <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
  </pre>

  <?php endif ?>

<?php else: ?>
<div id="error" class="not-found">
    <div class="blurb">
        <p>
            <strong>
            *** If you see this and you have just paid via paypal, please email us <a href="mailto:webmaster@cincyultimate.org?subject=<?php echo urlencode("[CUPA] Paypal Fix " . $_SERVER['REQUEST_URI']); ?>">webmaster@cincyultimate.org</a> we will get it fixed promptly.  ***
            </strong>
        </p>
        <p>
            The page you requested could not be found.  Please make sure you typed
            in the correct url.  If you believe this page should exist you can email
            the webmaster at <a href="mailto:webmaster@cincyultimate.org">webmaster@cincyultimate.org</a>.
        </p>
        <p>
            Here are some links to get you back on track<br/>
            <?php echo $this->partial('menu.phtml', array('user' => $this->user)); ?>
        </p>
    </div>
</div>
<?php endif; ?>
