            <?php if(count($this->data['contacts'])): ?>
            <table class="table table-condensed table-hover">
                <thead>
                    <tr>
                        <th class="span3">Name</th>
                        <th class="span2">Phone</th>
                        <th class="span2">&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->data['contacts'] as $contact): ?>
                    <tr>
                        <td><?php echo $this->escape($contact['first_name'] . ' ' . $contact['last_name']); ?></td>
                        <td><?php echo $this->escape($contact['phone']); ?></td>
                        <td>
                            <a class="btn btn-info btn-mini" href="<?php echo $this->url(array('contact_id' => $contact['id']), 'profile_edit_contact'); ?>"><i class="icon-edit icon-white"></i> Edit</a>
                            <a class="btn btn-danger btn-mini" onclick="return confirm('Are you sure you would like to remove this contact?');" href="<?php echo $this->url(array('contact_id' => $contact['id']), 'profile_remove_contact'); ?>"><i class="icon-trash icon-white"></i> Remove</a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <?php else: ?>
            <p>You do not have any emergency contacts set yet.</p>
            <?php endif; ?>
