<div id="page-banner">&nbsp;</div>

<?php if(Zend_Auth::getInstance()->hasIdentity()): ?>
<div class="row actions">
    <div class="span11">
        <div class="btn-group pull-right">
            <a class="btn" href="<?php echo $this->url(array('user_id' => $this->data['id']), 'page_profile_public'); ?>">Public Profile</a>
            <a class="btn" href="<?php echo $this->url(array(), 'profile_add_minor'); ?>">Add Minor</a>
            <a class="btn" href="<?php echo $this->url(array(), 'profile_add_contact'); ?>">Add Emergency Contact</a>
            <a class="btn" href="<?php echo $this->url(array(), 'profile_password'); ?>">Change Password</a>
        </div>
    </div>
</div>
<div class="row">
    <div class="offset1 span8">
        <h1><?php echo $this->escape($this->data['first_name'] . ' ' . $this->data['last_name']); ?></h1>
    </div>
</div>
<div class="page-content">
    <div class="row">
        <div class="offset1 span10">
        	<?php echo $this->partial('profile/menu.phtml', array('state' => $this->state));?>
            <?php echo $this->partial('profile/' . $this->state . '.phtml', array('state' => $this->state, 'data' => $this->data, 'form' => $this->form, 'user' => $this->user));?>
        </div>
    </div>
</div>
<?php else: ?>
<div class="row">
    <div class="hero-unit span9 offset1">
        <h1>Please login</h1>
        <p>You must be logged in to view your profile</p>
    </div>
</div>
<?php endif; ?>
