
            <?php if(count($this->data['leagues'])): ?>
            <table class="table table-condensed table-hover">
                <thead>
                    <tr>
                        <th>League</th>
                        <th>Team</th>
                        <th>Paid</th>
                        <th>Release</th>
                        <th>Waiver</th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->data['leagues'] as $league): ?>
                    <tr>
                        <td><?php echo $this->leaguename($league['league_id'], true, true, true, true); ?></td>
                        <td><?php if(!empty($league['team'])): ?><a href="<?php echo $this->url(array('league_id' => $league['league_id']), 'league_view'); ?>"><?php echo $this->escape($league['team']); ?></a> <?php else: ?>No Team<?php endif; ?></td>
                        <td><?php echo ($league['paid'] == 1) ? '<span class="text-success">Paid</span>' : '<span class="text-error">Owe $' . $league['cost'] . '</span>'; ?></td>
                        <td><?php echo ($league['release'] == 1) ? '<span class="text-success">Yes</span>' : '<span class="text-error">No</span>'; ?></td>
                        <td><?php echo ($this->hasUserSignedWaiver($this->user->id, $league['year'])) ? '<span class="text-success">Yes</span>' : '<span class="text-error">No</span>'; ?></td>
                        <td>
                            <?php if($this->isLeagueRegistrationOpen($league['league_id'])): ?>
                            <a href="<?php echo $this->url(array('league_id' => $league['league_id']), 'profile_edit_league'); ?>"><img title="Edit League Answers" src="<?php echo $this->baseUrl(); ?>/images/ico-edit.png"/></a>
                            <?php else: ?>
                            &nbsp;
                            <?php endif; ?>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <?php else: ?>
            <p>You have not registered for any leagues yet.</p>
            <?php endif; ?>
