            <ul class="nav nav-tabs">
                  <li<?php echo ($this->state == 'personal') ? ' class="active"' : ''; ?>><a href="<?php echo $this->url(array('state' => 'personal'), 'profile'); ?>"><strong>Personal Info</strong></a></li>
                  <li<?php echo ($this->state == 'status') ? ' class="active"' : ''; ?>><a href="<?php echo $this->url(array('state' => 'status'), 'profile'); ?>"><strong>Status</strong></a></li>
                  <li<?php echo ($this->state == 'minors') ? ' class="active"' : ''; ?>><a href="<?php echo $this->url(array('state' => 'minors'), 'profile'); ?>"><strong>Minors</strong></a></li>
                  <li<?php echo ($this->state == 'leagues') ? ' class="active"' : ''; ?>><a href="<?php echo $this->url(array('state' => 'leagues'), 'profile'); ?>"><strong>League Info</strong></a></li>
                  <li<?php echo ($this->state == 'contacts') ? ' class="active"' : ''; ?>><a href="<?php echo $this->url(array('state' => 'contacts'), 'profile'); ?>"><strong>Emergency Contacts</strong></a></li>
            </ul>
