            <?php if(count($this->data['minors'])): ?>
            <table class="table table-condensed table-hover">
                <thead>
                    <tr>
                        <th>Minor</th>
                        <th>Gender</th>
                        <th>Birthday</th>
                        <th>Nickname</th>
                        <th>Height</th>
                        <th>Level</th>
                        <th>Experience</th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->data['minors'] as $minor): ?>
                    <tr>
                        <td><?php echo $this->escape($minor['first_name'] . ' ' . $minor['last_name']); ?></td>
                        <td><?php echo (empty($minor['gender'])) ? '&nbsp;' : $this->escape($minor['gender']); ?></td>
                        <td><?php echo (empty($minor['birthday'])) ? '&nbsp;' : $this->escape($minor['birthday']); ?> (<?php echo $this->displayAge($minor['birthday']); ?>)</td>
                        <td><?php echo (empty($minor['nickname'])) ? '&nbsp;' : $this->escape($minor['nickname']); ?></td>
                        <td><?php echo (empty($minor['height'])) ? '&nbsp;' : $this->displayHeight($minor['height']); ?></td>
                        <td><?php echo (empty($minor['level'])) ? '&nbsp;' : $this->escape($minor['level']); ?></td>
                        <td><?php echo (empty($minor['experience'])) ? '&nbsp;' : $this->escape(date('Y') - $minor['experience'] . ' years'); ?></td>
                        <td>
                            <a class="btn btn-mini btn-info" href="<?php echo $this->url(array('minor_id' => $minor['id']), 'profile_edit_minor'); ?>"><i class="icon-edit icon-white"></i> Edit</a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <?php else: ?>
            <p>You have no minors associated to you.  Use the 'Add Minor' link to add one.</p>
            <?php endif; ?>
