<h1 class="profile">Change Password</h1>
<div class="profile-menu">
    &nbsp;
</div>
<div class="password-container">
    <form method="post">
        <?php foreach($this->form->getElements() as $element): ?>
        <div class="row">
            <?php echo $element; ?>
        </div>
        <?php endforeach; ?>
        <div class="row">
            <dt id="update-label"><label for="update">&nbsp;</label></dt>
            <dd id="update-element">
                <input class="button" type="submit" value="Change Password"/>
                <input class="button button-red" type="submit" name="cancel" value="Cancel"/>
            </dd>
        </div>
    </form>
</div>
