<?php echo $this->partial('admin/menu.phtml', array()); ?>
<div id="container">
    <h1>Duplicate User Accounts</h1>

    <div id="table">
        <?php foreach($this->users as $user): ?>
        <div class="user">
            <div class="name"><?php echo $this->escape($user[0]['first_name'] . ' ' . $user[0]['last_name']); ?></div>
            <div class="sub-header">
                <div class="sub-name">User (username)</div>
                <div class="email">Email</div>
                <div class="requested">Requested</div>
                <div class="activated">Activated</div>
                <div class="last-login">Last Login</div>
                <div class="action">Action</div>
            </div>
            <?php $this->cycle(array('odd', 'even')); ?>
            <?php foreach($user as $item): ?>
            <div class="row <?php echo $this->cycle()->next(); ?> <?php echo ($item['is_active'] == 1) ? 'active' : 'inactive'; ?>">
                <div class="sub-name"><a href="<?php echo $this->url(array('user_id' => $item['id']), 'page_profile_public'); ?>"><?php echo $this->escape($item['username']); ?></a><br/>&nbsp;</div>
                <div class="email"><?php echo $this->escape($item['email']); ?><br/>&nbsp;</div>
                <div class="requested"><?php echo date('Y-m-d H:i:s', strtotime($item['requested_at'])); ?></div>
                <div class="activated"><?php echo (empty($item['activated_at'])) ? 'Not<br/>Activated' : date('Y-m-d H:i:s', strtotime($item['activated_at'])); ?></div>
                <div class="last-login"><?php echo (empty($item['last_login']) or $item['last_login'] == '0000-00-00 00:00:00') ? 'Never<br/> Logged In' : date('Y-m-d H:i:s', strtotime($item['last_login'])); ?></div>
                <div class="action"><a href="<?php echo $this->url(array(), 'admin_duplicates'); ?>?user=<?php echo $item['id']; ?>"><img src="<?php echo $this->baseUrl(); ?>/images/ico-warning.png" title="Merge Accounts"/></a></div>
            </div>
            <?php endforeach; ?>
            <div class="clearfix">&nbsp;</div>
        </div>
        <?php endforeach; ?>
        <div class="clearfix">&nbsp;</div>
    </div>
</div>

