<div id="page-banner" class="about">&nbsp;</div>

<div class="row actions">
    <div class="span9 pull-left about">
        <h2>&nbsp;</h2>
    </div>
    <div class="span2">
        <div class="btn-group pull-right">
            <a class="btn" href="<?php echo $this->url(array(), 'admin_duplicates_email'); ?>"><i class="icon-envelope"></i> Send Notifications</a>
        </div>
    </div>
</div>
<div class="page-content">
    <div class="row">
        <div class="span2">
            <?php echo $this->partial('admin/menu.phtml', array('active' => 'duplicates')); ?>
        </div>
        <div class="span9">
            <h2>Duplicate User Accounts</h2>
            <?php if(count($this->users) > 0): ?>
            <?php foreach($this->users as $user): ?>
            <h3><?php echo $this->escape($user[0]['first_name'] . ' ' . $user[0]['last_name']); ?></h3>
            <div class="well well-small">
                <table class="table table-condensed">
                    <thead>
                        <tr>
                            <th class="span1">Username</th>
                            <th class="span1">Email</th>
                            <th class="span1" style="text-align: center;">Requested</th>
                            <th class="span1" style="text-align: center;">Activated</th>
                            <th class="span1" style="text-align: center;">Last Login</th>
                            <th class="span1">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($user as $item): ?>
                        <tr<?php echo ($item['is_active'] == 0) ? ' class="error"' : ''; ?>>
                            <td><a href="<?php echo $this->url(array('user_id' => $item['id']), 'page_profile_public'); ?>"><?php echo ($item['username']) ? $this->escape($item['username']) : 'Minor'; ?></a></td>
                            <td><?php echo $this->escape(substr($item['email'], 0, strpos($item['email'], '@') + 1)) . '<br/>' . $this->escape(substr($item['email'], strpos($item['email'], '@') + 1)); ?></td>
                            <td style="text-align: center;"><?php echo $this->escape($item['requested_at']); ?></td>
                            <td style="text-align: center;"><?php echo $this->escape($item['activated_at']); ?></td>
                            <td style="text-align: center;"><?php echo $this->escape($item['last_login']); ?></td>
                            <td><a class="btn btn-mini btn-warning" onclick="return confirm('Are you sure you would like to merge all user data to this account?');" href="<?php echo $this->url(array(), 'admin_duplicates'); ?>?user=<?php echo $item['id']; ?>"><i class="icon-user"></i><br/>Merge This</a></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <?php endforeach; ?>
            <?php else: ?>
            <p>There are no duplicate users in the system right now.</p>
            <?php endif; ?>
        </div>
    </div>
</div>
