<div id="page-banner" class="about">&nbsp;</div>

<div class="row actions">
    <div class="span9 pull-left about">
        <h2>&nbsp;</h2>
    </div>
    <div class="span2">
        <div class="btn-group pull-right">
            &nbsp;
        </div>
    </div>
</div>
<div class="page-content">
    <div class="row">
        <div class="span2">
            <?php echo $this->partial('admin/menu.phtml', array()); ?>
        </div>
        <div class="span8">
        </div>
    </div>
</div>


