<div id="page-banner" class="about">&nbsp;</div>

<div class="row actions">
    <div class="span9 pull-left about">
        <h2>&nbsp;</h2>
    </div>
    <div class="span2">
        <div class="btn-group pull-right">
        </div>
    </div>
</div>
<div class="page-content">
    <div class="row">
        <div class="span2">
            <?php echo $this->partial('admin/menu.phtml', array('active' => 'duplicates')); ?>
        </div>
        <div class="span9">
            <h2>Move League Player</h2>
            <?php echo $this->partial('admin/league_steps.phtml', array('state' => $this->state));?>
            <?php if($this->state == 'done'): ?>
            <p>
                Are you sure that you want to move <strong><?php echo $this->fullname($this->session->src_player['league_member_id'], true); ?></strong> from <strong><?php echo $this->leaguename($this->session->src_league['league_id'], true, true, true, true); ?></strong> to <strong><?php echo $this->leaguename($this->session->target_league['league_id'], true, true, true, true); ?></strong>
                <?php if(!empty($this->session->target_team['league_team_id'])): ?>
                and on the team <strong><?php echo $this->getLeagueTeamName($this->session->target_team['league_team_id']); ?></strong>.
                <?php else: ?>
                and on <strong>no team</strong>
                <?php endif; ?>
            </p>
            <?php endif; ?>
            <?php echo $this->form; ?>
        </div>
    </div>
</div>
