            <div class="row">
                <br/><br/><br/>
            </div>
            <ul class="nav nav-list well well-small">
                <li class="nav-header">Admin Actions</li>
                <li<?php echo ($this->active == 'browser') ? ' class="active"' : ''; ?>><a href="<?php echo $this->url(array(), 'admin_browser'); ?>">Browser Data</a></li>
                <li<?php echo ($this->active == 'duplicates') ? ' class="active"' : ''; ?>><a href="<?php echo $this->url(array(), 'admin_duplicates'); ?>">Duplicate Users</a></li>
            </ul>
