<h1>CUPA Administration</h1>
<div id="list">
    <h2>Reports:</h2>
    <ul>
        <li><a class="button" id="browser-data" href="<?php echo $this->url(array(), 'admin_browser'); ?>">Browser Data</a></li>
        <li><a class="button" id="unpaid-users" href="<?php echo $this->url(array(), 'admin_unpaid'); ?>">Unpaid Players</a></li>
        <li><a class="button" id="duplicate-users" href="<?php echo $this->url(array(), 'admin_duplicates'); ?>">Duplicate Users</a></li>
    </ul>
</div>
