            <div class="row">
                <br/><br/><br/>
            </div>
            <ul class="nav nav-list well well-small">
                <li class="nav-header">Admin Actions</li>
                <?php if($this->hasRole('admin')): ?>
                <li<?php echo ($this->active == 'browser') ? ' class="active"' : ''; ?>><a href="<?php echo $this->url(array(), 'admin_browser'); ?>">Browser Data</a></li>
                <li<?php echo ($this->active == 'duplicates') ? ' class="active"' : ''; ?>><a href="<?php echo $this->url(array(), 'admin_duplicates'); ?>">Duplicate Users</a></li>
                <?php endif; ?>

                <?php if($this->isLeagueDirector()): ?>
                <li<?php echo ($this->active == 'unpaid') ? ' class="active"' : ''; ?>><a href="<?php echo $this->url(array(), 'admin_unpaid'); ?>">Un-paid List</a></li>
                <?php endif; ?>

                <?php if($this->hasRole('admin') or $this->hasRole('manager')): ?>
                <li<?php echo ($this->active == 'users') ? ' class="active"' : ''; ?>><a href="<?php echo $this->url(array(), 'admin_users'); ?>">Users</a></li>
                <li<?php echo ($this->active == 'pages') ? ' class="active"' : ''; ?>><a href="<?php echo $this->url(array(), 'admin_pages'); ?>">Pages</a></li>
                <li<?php echo ($this->active == 'league_players') ? ' class="active"' : ''; ?>><a href="<?php echo $this->url(array(), 'admin_league_players'); ?>">League Players</a></li>
                <?php endif; ?>
            </ul>
