<div id="page-banner" class="about">&nbsp;</div>

<div class="row actions">
    <div class="span9 pull-left about">
        <h2>&nbsp;</h2>
    </div>
    <div class="span2">
        <div class="btn-group pull-right">
            <a class="btn btn-small" href="<?php echo $this->url(array(), 'admin_page_add'); ?>"><i class="icon-book"></i> Add Page</a>
        </div>
    </div>
</div>
<div class="page-content">
    <div class="row">
        <div class="span2">
            <?php echo $this->partial('admin/menu.phtml', array('active' => 'pages')); ?>
        </div>
        <div class="span9">
            <h2>User List</h2>
            <div class="pull-right">
                <?php echo $this->form; ?>
            </div>
            
            <?php if(count($this->pages) > 0): ?>
            <table class="table table-condensed table-hover">
                <thead>
                    <tr>
                        <th>Page</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->pages as $page): ?>
                    <tr<?php echo ($page->is_visible == 0) ? ' class="error"' : ''; ?>>
                        <td><?php echo $this->escape($page->title); ?></td>
                        <td>
                            <a class="btn btn-mini btn-info" href="<?php echo $this->url(array('page' => $page->name), 'page_view'); ?>"><i class="icon-edit icon-white"></i> View</a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <?php echo $this->paginationControl($this->pages,
                                    'Sliding',
                                    'admin/pagination.phtml'); ?>
            <?php else: ?>
            <p>There are no users in the system right now.</p>
            <?php endif; ?>
        </div>
    </div>
</div>
