<div id="page-banner" class="about">&nbsp;</div>

<div class="row actions">
    <div class="span9 pull-left about">
        <h2>&nbsp;</h2>
    </div>
    <div class="span2">
        <div class="btn-group pull-right">
            <a class="btn btn-small" href="?export=1"><i class="icon-list"></i> Export List</a>
        </div>
    </div>
</div>
<div class="page-content">
    <div class="row">
        <div class="span2">
            <?php echo $this->partial('admin/menu.phtml', array('active' => 'volunteers')); ?>
        </div>
        <div class="span9">
            <h2>Volunteer List</h2>

            <?php if(count($this->volunteers) > 0): ?>
            <table class="table table-condensed table-hover">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->volunteers as $volunteer): ?>
                    <tr>
                        <td><?php echo $this->escape($volunteer['first_name'] . ' ' . $volunteer['last_name']); ?></td>
                        <td><?php echo (empty($volunteer['email'])) ? $this->escape($volunteer['parent_email']) : $this->escape($volunteer['email']); ?></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <?php echo $this->paginationControl($this->volunteers,
                                    'Sliding',
                                    'admin/pagination.phtml'); ?>
            <?php else: ?>
            <p>There are no volunteers in the system right now.</p>
            <?php endif; ?>
        </div>
    </div>
</div>
